### ISSUE TITLE
Make sure Python 3 version of Debian package is installed in ev3dev image

### ISSUE THREAD

**Issue by bittner** [rhempel/ev3dev-lang-python#106]
In the current ev3dev image ([ev3-ev3dev-jessie-2015-12-30](https://github.com/ev3dev/ev3dev/releases/tag/ev3dev-jessie-2015-12-30)) `env3dev` is not importable from python3:
``` python
robot@ev3dev:~$ python3
>>> import ev3dev
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ev3dev'
>>> 
```
With python2 importing works. Ideally this should work identically for either Python version.

See [topikachu/python-ev3#63](https://github.com/topikachu/python-ev3/issues/63#issuecomment-168333561) for step-by-step instructions to reproduce the issue.

**Comment by rhempel** [comment]
Agreed - the package does not install the binding scripts in the Python3 library area, so of course it's not found. I'm looking into this now.

**Comment by rhempel** [comment]
I have added a workaround to the GitHub README.rst page [here](https://github.com/rhempel/ev3dev-lang-python/blob/update-readme-content/README.rst)

We'll make sure that the next version of ev3dev has both Python2 and Python3 support for this binding out of the box.
