### ISSUE TITLE
BrickPi Analog Sensors?

### ISSUE THREAD

**Issue by antonvh** [rhempel/ev3dev-lang-python#115]
I try to get a touch sensor to work on the brickpi, but I'm a little lost. What Class should I use? Where is the sensor in /sys/class ?

```
>>> from ev3dev.auto import TouchSensor, INPUT_4
>>> ts = TouchSensor(INPUT_4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 1664, in __init__
    Device.__init__(self, self.SYSTEM_CLASS_NAME, name_pattern, name_exact, driver_name=['lego-ev3-touch', 'lego-nxt-touch'], **kwargs)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 180, in __init__
    name = next(list_device_names(classpath, name_pattern, **kwargs))
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 123, in list_device_names
    for f in os.listdir(class_path):
OSError: [Errno 2] No such file or directory: '/sys/class/lego-sensor'
```

```
anton@ev3dev-rpi:~$ ls /sys/class/
backlight        graphics          iscsi_session    raw          thermal
bcm2708_vcio     hidraw            iscsi_transport  rfkill       tty
bcm2835-gpiomem  i2c-adapter       leds             rtc          uio
bdi              i2c-dev           lego-port        scsi_device  vc
block            ieee80211         mem              scsi_disk    vc-cma
bsg              input             misc             scsi_host    vc-mem
dc-motor         iscsi_connection  mmc_host         sound        vc-sm
devcoredump      iscsi_endpoint    net              spi_master   vchiq
dma              iscsi_host        power_supply     spidev       vtconsole
gpio             iscsi_iface       pwm              tacho-motor  watchdog
```

**Comment by dlech** [comment]
BrickPi has no auto-detection capabilities. You have to manually put the input port into `ev3-analog` or `nxt-analog` mode first depending on which touch sensor you are using. Since the EV3 touch sensor is the only supported ev3-analog sensor, the correct driver will be automatically loaded. Since there are lots of NXT analog sensors, a generic driver will be loaded. you have to manually load the correct driver using the ports `set_device` attribute. Also, there is an outstanding bug with the NXT touch sensor on BrickPi (ev3dev/ev3dev#374).

**Comment by antonvh** [comment]
OK. I got a little further:
```
$ python
>>> p = Device('lego-port', name_pattern='*', address='in4') 
>>> p.connected
True
>>> p.set_attr_string('mode', 'ev3-analog')
>>> p.set_attr_string('set_device', 'lego-ev3-touch')
>>> s = Sensor(address='in4') #Now that the lego port is initialised a lego-sensor appears in /sys/class
>>> s.connected
True
>>> s.get_attr_int('value0')
0
```

( I have to go via the Device class, because LegoPort class is broken. The classname has an underscore while it should be a dash. Furthermore the brickpi input addresses are broken. They should be just 'in4' instead of 'ttyAMA0:in4')

Now I'm stuck again, because the value doesn't change when pressing or depressing the button. No change in `bin_data` either... Guess I'll have to wait for the other bug fix...

**Comment by ddemidov** [comment]
Issue with `lego-port` was fixed by @G33kDude in ev3dev/ev3dev-lang#132. I almost sure we did pull the change here at some point. @rhempel, could you regenerate the bindings?

@antonvh, can you open a new issue for input port names?

**Comment by antonvh** [comment]
Will do! Thanks for the help

**Comment by ddemidov** [comment]
Actually, the change from ev3dev/ev3dev-lang#132 did not make it into the current develop branch for some reason. See https://github.com/ev3dev/ev3dev-lang/pull/132#issuecomment-170511875

**Comment by rhempel** [comment]
I'll merge and regenerate tonight - thanks for locating the defect!

**Comment by antonvh** [comment]
I suppose it's fixed now.
