### ISSUE TITLE
How to make changes to ev3dev/core.py

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#117]
Is it acceptable to make changes directly to ev3dev/core.py or should all changes be made via the templates?  If the former how can I tell which sections can/cannot be modified?  If the latter is if ok for me to add a helper.py (I'm not particular about the name) to that directory?

I have a Tank class that I would like to add that serves as a base class for TRACK3R.

**Comment by rhempel** [comment]
Consider adding a Tank Class as a demo or higher level wrapper that the user includes separately.

The goal of `core.py` is in the name - core functionality. If you add tank drive (and then a dozen more) specialty helper classes it affects load time and the possibility of defects and surprises for everyone.

I'd rather see a generic differential drive class that is built on the core files, rather than core files that include a differential drive class.

I'll be very interested to see what you come up with :-)

**Comment by ddemidov** [comment]
Also, to answer the original question, anything between a pair of comments like
```py
# ~autogen <template-file> <parameters>
...
# ~autogen
```
is autogenerated, and should not be touched directly. Changes, if any, should go into the corresponding template file.

**Comment by rhempel** [comment]
Thanks for actually answering the question @ddemidov ! Changes to code between those marks goes in the template file. That's why I asked for the `autogen` system to be able to strip out the `autogen`ed code so that you could more clearly see what's in the source file.

**Comment by dwalton76** [comment]
Cool, thanks for the info.  How about I make a demo/official_lego_projects/ directory and put my Tank class in a common.py file there and my TRACK3R classes in a TRACK3R.py?  I think it would be good to have sample programs for TRACK3R, GRIPP3R, EV3RSTORM, SPIK3R and R3PTR and the Tank class makes TRACK3R, GRIPP3R, and EV3STORM pretty easy. Of the bonus models:
http://www.lego.com/en-us/mindstorms/build-a-robot

the Tank class could also be used for BOBB3E, KRAZ3, EV3D4 and ROBODOZ3R.

**Comment by WasabiFan** [comment]
> ...is autogenerated, and should not be touched directly. Changes, if any, should go into the corresponding template file.

If there are simple changes that you'd like to see added to the templates, it would probably work if you opened an issue and posted a snippet of what you want as the end result, and then @rhempel or @ddemidov can go and implement it.
