### ISSUE TITLE
http://python-ev3dev.readthedocs.org/en/latest/ missed link for LED docs

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#123]
Under content is:

    Other classes
        Power Supply
        Button
        Sound
        Screen

When you follow the link for "Other classes" you see that the LED docs are there first.

**Comment by ddemidov** [comment]
Thanks! Addressed in #124.

**Comment by rhempel** [comment]
Thks @ddmeidov - I'll be merging these PRs today or tomorrow
