### ISSUE TITLE
speed regulation naming

### ISSUE THREAD

**Issue by 251** [rhempel/ev3dev-lang-python#136]
The Motor class defines a property "speed_regulation_enabled" while most documents and the sysfs use "speed_regulation". What's the reason for this naming scheme? I got confused while testing the wiki examples for the shell.

**Comment by ddemidov** [comment]
I had the same feeling, but was too lazy to report it :). I agree that `speed_regulation='on'` is self-explanatory and sounds better than `speed_regulation_enabled='on'`.

**Comment by ddemidov** [comment]
But this issue should be reported against https://github.com/ev3dev/ev3dev-lang.

**Comment by WasabiFan** [comment]
Makes sense -- the other name is probably just a vestige of previous work that was never corrected.

**Comment by ddemidov** [comment]
@rhempel, wasn't the plan to always keep speed regulation on (and remove the sysfs attribute) and only run unregulated in direct mode? In this case this is a non issue after next drivers update?

**Comment by rhempel** [comment]
`speed_regulation` attribute is going away in the next release - all commands (except for `run-direct`) will use the `speed_sp` to handle the motion, and will be regulated by default.

**Comment by ensonic** [comment]
Is ```speed_regulation=on``` currently already the default for e.g. ```run_forever```? If so I could already remove the use.

**Comment by rhempel** [comment]
No, not yet - next driver/kernel release
