### ISSUE TITLE
PS 4 Controller via Bluetooth

### ISSUE THREAD

**Issue by NielsAMG** [rhempel/ev3dev-lang-python#137]
Can I connect a PS4 DS4 Controller via Bluetooth with ev3dev? And with which commands can I check the values from the controller in Python?

**Comment by dlech** [comment]
Yes you can use that controller. If you have a knockoff like in ev3dev/ev3dev#536, you will have to wait for the next kernel release. For python, [pygame](http://www.pygame.org/hifi.html) seems popular for this sort of thing. For more of a low level interface you can use [python-evdev](http://python-evdev.readthedocs.org/en/latest/).

**Comment by NielsAMG** [comment]
And how can I connect it with the ev3 brick? In the brickman Bluetooth menu?

**Comment by dlech** [comment]
I don't know. You will just have to try it an see. Some game controllers require special handling of the connection, but the bluetooth menu in Brickman should handle most cases.
