### ISSUE TITLE
Nxt Compass sensor shows bad values

### ISSUE THREAD

**Issue by markosko** [rhempel/ev3dev-lang-python#138]
bin_data_format shows signed 8bit number and 
expected values vs returned by value() function 
0=0, 90=around 56, 180= around 124, 270= around -104

Values are from 0-127 then jump to -128 and from there to -77 and then back to 0

**Comment by dlech** [comment]
General bugs should be posted in <https://github.com/ev3dev/ev3dev/issues> this has nothing to do with python). Please also see <http://www.ev3dev.org/support/>. Also, a link to the sensor documentation would be helpful.

**Comment by markosko** [comment]
Thanks probably found where is problem
