### ISSUE TITLE
Screen().img got renamed to Screen()._img and is now also missing from the docs.

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#142]
In open-roberta I was using this code to show image in the screen:
``` python
image = Image.frombytes('1', (178, 128), IMAGES[picture], 'raw', '1;IR', 0, 1)
lcd = ev3dev.Screen()
lcd.img.paste(image, (0, 0))
lcd.update()
```
I could fix this by now doing
```patch
- lcd.img.paste(image, (0, 0))
+ lcd._img.paste(image, (0, 0))
```
I can't find when that changed. Anyway this is not about blaming :) Can we expose this in a nicer way properly?

**Comment by ddemidov** [comment]
The field was always intended to be internal, hence the missing docs. What you are doing makes sense though, so we can expose the field either directly or with a property. Care to make a PR?

**Comment by ddemidov** [comment]
It looks like the change came with the switch from old boost-based implementation to the new pure python one.

**Comment by ensonic** [comment]
Yep, I'll make a PR. Shall we just expose img like we expose draw or add a proxy method for img.paste()?

**Comment by ddemidov** [comment]
Is there anything else potentially useful in the `Image` inteface besides `paste()`? I have little experience with the Pillow library.

**Comment by ensonic** [comment]
Here is the reference: https://pillow.readthedocs.org/en/3.0.0/reference/Image.html - I think it is unfortunate that draw does not have a method to blit an image.

**Comment by ddemidov** [comment]
I think just exposing the image field would be both easier and future proof :).
