### ISSUE TITLE
new project: ev3-mapping

### ISSUE THREAD

**Issue by alesolano** [rhempel/ev3dev-lang-python#144]
Hello!

Some friends and I are working in a project with the goal of doing some mapping with the EV3. The project is called [ev3-mapping](https://github.com/alesolano/ev3-mapping) and we use, of course, ev3dev and this Python library.

It's our first project with GitHub, Python, documentation and everything, so any advice or help is very welcomed!!

---
This weekend we'll be coding some classes that could be useful for everyone (or maybe they have already been created), like a class for any Differential Robot and other for a EXPLOR3R robot.

**Comment by jabrena** [comment]
Hi, take a look this video from a student in a Imperial course.
https://www.youtube.com/watch?v=5dL6v2m0zH8

**Comment by alesolano** [comment]
That's brilliant! Pfff, they have done a lot of cool stuff. This project on localization it's what I'd like to achieve in a near future: https://www.youtube.com/watch?v=AsIN9RMKYPE 
That's why I'm starting with the ev3-mapping project.

Anyway, I just took a look at your work... amazing!! I am currently working on a Occupancy grid map, like the one you describe on the [README](https://github.com/jabrena/livingrobots#local-navigation) of your livingrobots repository.
And I have encountered two dilemmas so far. They are explained [here](https://github.com/alesolano/ev3-mapping/wiki#grid-map). Can you take a look, please? :grin:

**Comment by dwalton76** [comment]
Looks cool :)
