### ISSUE TITLE
Ps4 Controller 

### ISSUE THREAD

**Issue by NielsAMG** [rhempel/ev3dev-lang-python#146]
If I print the events Form the controller allthing is great, but the two Joysticks dont work. All the other buttons work.

**Comment by dlech** [comment]
Have you used `evtest` from the command line to spy on the controller? They joysticks are most likely an absolute axis event, which is a different kind of event and has to be read differently.

**Comment by antonvh** [comment]
Here's a tutorial for a PS3 controller. http://www.ev3dev.org/docs/tutorials/using-ps3-sixaxis/ Let me know what is different for a PS4 controller, so I can add it. A similar mapping would be nice. Can you make that?

**Comment by fryfrog** [comment]
I'm experimenting with this now, did anyone ever get a PS4 controller working? When I run 'evtest /dev/input/event0' I get an expected list of buttons and axises, but no events... *except* that the touchpad works. Moving your finger on it creates events, as does pressing it. But no buttons or joysticks or triggers register. Even in a simple python script doing the same thing. :/
