### ISSUE TITLE
Missing Color Sensor functions

### ISSUE THREAD

**Issue by demar42** [rhempel/ev3dev-lang-python#150]
Hi there,

I have been using this python language with my ev3, and first off I'd like to commend the creators on how great it is! Thank you for creating this.

I have been trying to use the ColorSensor class in my program, and in following the docs, I have noticed that several functions that are documented are not there, such as `green()`, `color()` and `reflected_light_intensity()`. Could you please tell me where these functions have been moved to, or if they have been removed?

I'm using the version of python that comes with the latest version of ev3dev

EDIT: Here is where I found the docs http://ev3dev-lang.readthedocs.org/projects/python-ev3dev/en/latest/sensors.html#sensor

Thank you!

**Comment by ddemidov** [comment]
These functions [are present](https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/core.py#L1586) in the develop branch of the library. They probably just have not been published as a debian package yet.

You can in principle install the develop version of the package by (not tested)
```
# apt-get uninstall python-ev3dev
# git clone -b develop https://github.com/rhempel/ev3dev-lang-python
# cd ./ev3dev-lang-python
# python setup.py install
```

**Comment by demar42** [comment]
Thank you, this has solved my issue!
