### ISSUE TITLE
BrickPi with Raspberry Pi3 and python:  current_platorm unsupported

### ISSUE THREAD

**Issue by JorgePe** [rhempel/ev3dev-lang-python#158]
Trying to use MediumMotor in python

`AttributeError: 'MediumMotor' object has no attribute '_path'`

 I think auto.py needs an extra platform check for the Pi3. This script:

```
from ev3dev.auto import *
print current_platform()
```
outputs:
`unsupported`

**Comment by dlech** [comment]
see ev3dev/ev3dev#412
