### ISSUE TITLE
Motors not working from breaking update changes to ev3dev

### ISSUE THREAD

**Issue by psychemedia** [rhempel/ev3dev-lang-python#159]
Having updated ev3dev, python bindings for motors fail to work due to [breaking changes](http://www.ev3dev.org/news/2016/04/11/Kernel-Release-Cycle-10/) but I don't know enough to work out what I need to change where to make the motors work...?

thanks
---tony

**Comment by edmundronald** [comment]
@psychemedia you can fix by downgrading the kernel. Why, I don't know. See the end of this
https://github.com/rhempel/ev3dev-lang-python/issues/130

**Comment by WasabiFan** [comment]
Yes, downgrading should fix the issue. The problem is that this library (the Python library) hasn't yet been updated to work with the newer kernel; using the older one is the temporary solution. @rhempel is working on getting it updated.

**Comment by dlech** [comment]
`run-direct` is broken in the kernel driver: https://github.com/ev3dev/ev3dev/issues/621

**Comment by edmundronald** [comment]
btw, dumb question, where are there clean docs for the current user-level ev3  functions, and which IDE d'you recommend running via SSH, that would preferably be able to figure out code completions etc? I think I used pico last time round, but it gets old. 

Edmund

**Comment by nadehi18** [comment]
This is a very annoying issue lol, and @edmundronald I use atom with the atom-sync package installed for it, which once setup saves a local copy of the files you are working on, and then copies them onto the robot or computer depending on which was updated last.  Just a note, for the atom-sync you need rsync installed on your computer and the ev3 for it to work...

**Comment by rhempel** [comment]
@edmundronald and @nadehi18, please open a new issue to discuss IDEs - this is for the Python binding not being up to date with the kernel, and my inability to find spare time lately to fix that. Hopefully this weekend I can get some more traction.

@dlech, have you got a proposed fix for the `run-direct` issue into a branch for us to try?

**Comment by WasabiFan** [comment]
@rhempel https://github.com/ev3dev/lego-linux-drivers/commit/efd2269e8d26df29f5c73a507f7f33b2bdd8380e

Looks like it's in master over there.

**Comment by edmundronald** [comment]
@rhempel and @nadehi18 I have created a new issue for IDEs.
https://github.com/rhempel/ev3dev-lang-python/issues/160

**Comment by ValorNaram** [comment]
I've create a motor class, that works!
[ev3dev-python-API] (https://github.com/ValorNaram/ev3dev-python-API)
Its current in debug mode and uses the tacho-motor driver (`/sys/class/tacho-motor`)
