### ISSUE TITLE
PiStorms display is blank, boot stops at "Started Update UTMP about System Runlevel Changes"

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#168]
I am using a raspberry pi2 that is running the latest and greatest (did apt-get update, upgrade, dist-upgrade). When I boot the pi though the pistorms display is solid white and stays that way.  I hooked up the pi to my TV and bootup is stalled at "Started Update UTMP about System Runlevel Changes".  Google tells me that is video/X related which adds up with the pistorms display not working.

Is anyone else hitting this with their PiStorms?

**Comment by WasabiFan** [comment]
I think you should probably post this question in the main ev3dev repo, because it's not a problem with the Python library. Also, make sure you include the information that the issue template in the ev3dev repo asks for.

**Comment by dwalton76** [comment]
Great point...I am so used to posting issues only here I did it out of habit
