### ISSUE TITLE
Stop_action 'hold' does not seem to work

### ISSUE THREAD

**Issue by Zordid** [rhempel/ev3dev-lang-python#174]
Hello!
I am having huge difficulties to do a "simple" absolute positioning with my motors.

When issuing something like:
`motor.run_to_abs_pos(position_sp=abs_position, speed_sp=speed, stop_action='hold')`
the motor overshoots MASSIVE amounts and does not hold.

The only way I could "almost" make it with only little overshoot is something like this:

```
motor.ramp_up_sp=1000
motor.ramp_down_sp=1000
motor.run_to_abs_pos(position_sp=abs_position, speed_sp=speed, stop_action='brake')
```

It seems to completely ignore "hold" stop action. When putting anything in there, like stop_action='xxx' it behaves exactly the same...

Does anybody have an idea?
Thanks!

**Comment by rhempel** [comment]
What is your kernel version (`uname -a`)

**Comment by WasabiFan** [comment]
Please answer the questions in the issue template instead of deleting them. When you are asking anything that involves the kernel and its functionality, we need to know what platform you are running on and what kernel version you are using. The image name also is important.

**Comment by dlech** [comment]
@WasabiFan, I don't think this repository has an issues template.

**Comment by Zordid** [comment]
Of course the latest, 11...

Am 12. Juni 2016 18:22:43 MESZ, schrieb Ralph Hempel <notifications@github.com>:

**Comment by oakie** [comment]
I have the same issue. It seems to work fine using bash: `echo hold > /sys/class/tacho-motor/motor0/stop_action` but doing the same thing in python behaves like coast.

**Comment by dwalton76** [comment]
@Zordid or @oakie are you still seeing this with the latest ( -18) kernel? I use stop_action='hold' a lot, everything is good for me.

**Comment by dwalton76** [comment]
Please re-open if this is still an issue
