### ISSUE TITLE
dont work with LargeMotor on ev3 

### ISSUE THREAD

**Issue by Hchristian** [rhempel/ev3dev-lang-python#175]
I use the jessie 2015-30-12. And i cannot work with LargeMotor. The brick start normally, update are ok, python3.4 is ok.

`import ev3

from ev3 import lego

from ev3.lego import LargeMotor

Left=LargeMotor('outA')

Traceback (most recent call last):

File "", line 1, in 

File "build/bdist.linux-armv5tejl/egg/ev3/lego.py", line 211, in init

File "build/bdist.linux-armv5tejl/egg/ev3/ev3dev.py", line 334, in init

ev3.ev3dev.NoSuchMotorError: No such motor port=outA type=lego-ev3-l-motor>`

**Comment by dlech** [comment]
ping @ddemidov: does this look like your old ev3dev-lang-python?

**Comment by ddemidov** [comment]
> does this look like your old ev3dev-lang-python?

No. It does look like [topikachu/python-ev3](https://github.com/topikachu/python-ev3/blob/master/ev3/ev3dev.py#L24) though. @Hchristian, it looks like you have the wrong library. You need to either open the issue in [python-ev3](https://github.com/topikachu/python-ev3/issues/new) repo, or install this library (see [here](https://github.com/rhempel/ev3dev-lang-python#python2x-and-python3x-compatibility) for instructions).
