### ISSUE TITLE
TouchSensor not found

### ISSUE THREAD

**Issue by evaldas-raisutis** [rhempel/ev3dev-lang-python#176]
When I try to assign Touch Sensor to a variable, it throws an error. Default,  install with apt-get upgade run.  evb-ev3dev-jessie-2016-01-25

![qq](https://cloud.githubusercontent.com/assets/3714332/16541778/5d9bfd30-408d-11e6-9bcc-2397b072707d.PNG)

**Comment by dlech** [comment]
You are using FatcatLab EVB on BeagleBone?

**Comment by evaldas-raisutis** [comment]
Hmm, I downloaded the image from the main link on "Getting Starter", but I can see now same link gives a different image file. Spooky stuff.

**Comment by WasabiFan** [comment]
@evaldas-raisutis how confident are you that the link you clicked before was the one for the EV3? While it may seem outlandish to think that the link changed by itself, as the designer of those download buttons I can say that it's definitely possible (although obviously it is a problem if that is what happened). If you think that it changed, I will be needing to go and see if I can repro it.

**Comment by evaldas-raisutis** [comment]
I definitely can't say for sure that was the case,  because mistakes happen
hehe. But I haven't worked with ev3 or anything similar before,  do I was
just following the guide. I'm not sure how I could've managed to find the
wrong image..  I tried it today,  and it downloaded the right one.

**Comment by WasabiFan** [comment]
OK, thanks for the tip; I'll check it out and make sure that the links are always correct.
