### ISSUE TITLE
Motor not working

### ISSUE THREAD

**Issue by tjhgit** [rhempel/ev3dev-lang-python#177]
System information:

I am using: LEGO MINDSTORMS EV3
I installed ev3dev using this image file: ev3-ev3dev-jessie-2015-12-30.img
My kernel version is: 4.4.13-12-ev3dev-ev3 (via apt-get dist-upgrade)
My host computer is running: OS X 10.11.5
I am connecting using: USB

Absolutely nothing happens with this code:
m = ev3.LargeMotor('outA')
m.run_timed(time_sp=3000, duty_cycle_sp=75)

While this works:
ev3.Sound.speak('Welcome to the EV3DEV project!').wait()

It seems to me that the ev3dev kernel evolves faster than the lang packages. Should I not use dost-upgrade in the future?
Should I downgrade to earlier kernel? What kernel does ev3dev-lang-python work with?

**Comment by 20oskar00** [comment]
+1

**Comment by dwalton76** [comment]
@tjhgit please re-open if this is still an issue with the latest kernel and latest from the ev3dev-lang-python develop branch.
