### ISSUE TITLE
Run_forever Ev3 Issue

### ISSUE THREAD

**Issue by BookBytes** [rhempel/ev3dev-lang-python#178]
I am currently using the Large Motor for the Ev3 in port 'outA' (aka Port A). When I ask the motor to run forever, it only runs for around 1 second and then stops. To keep it going I have to put the run_forever function call in a while loop but I am not sure why this is necessary. I'm not sure why this is happening.

My code is as follows. I called an 'interpret_command' function that I wrote which checks to see if a touch sensor in port 1 is pressed or not and if it is, responds by turning on the motor. It contains the following lines with regards to the motor (pseudocode):
```
        m=ev3.LargeMotor('outA')
if  touch sensor is pressed: 
        m.run_forever(duty_cycle_sp=40)
```
Edit: It looks like the same is occurring with the medium motor for the ev3. Do I possibly have an old version of something?

Thank you in advance!

**Comment by dwalton76** [comment]
I think what is happening here is your program is exiting which shuts off the motor.  Try adding the following to the end
```
raw_input("Paused until you press <ENTER>")
```

If that does not fix it feel free to re-open
