### ISSUE TITLE
Python3-pil not found?

### ISSUE THREAD

**Issue by Master-Matt** [rhempel/ev3dev-lang-python#179]
I have been trying to write my first program for ev3dev on python, but I want to work in python 3. I'm pretty inexperienced with Linux, but I've used python for a while now.
when using the following sudo command I get an error that says "unable to locate package"
sudo apt-get install python3-pil

When I run the following command I get  the error "Could not find suitable distribution for Requirement.parse('python-ev3dev')"
sudo python3 -m easy_install python-ev3dev
Not sure if I'm doing something wrong or if the repo is not working currently.
Thanks!

**Comment by dlech** [comment]
You need to be connected to the Internet and run `sudo apt-get update` first.

**Comment by Master-Matt** [comment]
Yup. Did that. got a good update. some were ignored though.

**Comment by Master-Matt** [comment]
Ah, now I seem to have a connection issue, although the connection looks good from the brick.

**Comment by Master-Matt** [comment]
Sorry there Dave, I'll close this. Always need to restart before opening my mouth! : )
