### ISSUE TITLE
Sumoeyes on python?

### ISSUE THREAD

**Issue by Master-Matt** [rhempel/ev3dev-lang-python#181]
I am trying to use mindsensors' sumoeyes with ev3dev. I'm wondering what the best course of action is to use it in my program. I found a a couple of classes for sumoeyes, but I'm wondering if I should just use the lego-sensor class. Has anyone made a driver for sumoeyes for ev3dev?

**Comment by dlech** [comment]
There is not an ev3dev driver for sumoeyes. You could write one or you can use use python-smbus to communicate with the sensor directly.
