### ISSUE TITLE
On BrickPi, motor output is ttyAMA0:MA not outA or ttyAMA0:outA

### ISSUE THREAD

**Issue by fryfrog** [rhempel/ev3dev-lang-python#184]
Working with @dlech in #ev3dev, we figured this out.

**Comment by ddemidov** [comment]
Is it just `outA`'s problem? Shoud `outB` - `outD` be changed as well?

**Comment by fryfrog** [comment]
Right, sorry it is all of them. And I made a pull request to fix it, https://github.com/rhempel/ev3dev-lang-python/pull/185

**Comment by WasabiFan** [comment]
Can this be closed? It looks like #185 was merged.
