### ISSUE TITLE
Mindsensors IMU Tilt data

### ISSUE THREAD

**Issue by Master-Matt** [rhempel/ev3dev-lang-python#189]
I noticed on the ev3dev page for the mindsensors IMU that it lists the tilt data as 0 to 180 degrees. Ive been datalogging, and the values i get range from -127 to 128. This actually matches the documentation [here](http://www.mindsensors.com/pdfs/AbsoluteIMU-User-Guide.pdf). So is this python being funky, or just an error in documentation?

**Comment by dlech** [comment]
This is not a python issue, this is a driver issue. I think the intention was to add a lookup table to convert the raw values (-127 to -128) to an actual angle. It looks like this [is implemented](https://github.com/ev3dev/lego-linux-drivers/blob/master/sensors/nxt_i2c_sensor_defs.c#L147).

If you are using the `bin_data` attribute, then it expected that you would get the raw values (-127 - 128).

If you are using `value0` then it is expected to get 0 to 180. If this is not the case, please open an issue at https://github.com/ev3dev/ev3dev/issues.
