### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by ddemidov** [rhempel/ev3dev-lang-python#197]
I've just noticed that API reference pages just contain section headers and no actual content (which should be autogenerated from python docstrings). Examples:

* http://python-ev3dev.readthedocs.io/en/latest/motors.html
* http://python-ev3dev.readthedocs.io/en/latest/other.html

I won't be able to look at the issue until I am back from vacation unfortunately.

**Comment by ddemidov** [comment]
Fixed the documentation. Needed to switch to python 3 as interpreter on readthedocs.org.

@ndward, http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/latest/spec.html should contain documentation for the latest version of the library. For example, screen class description is here: http://python-ev3dev.readthedocs.io/en/latest/other.html#screen.

**Comment by WasabiFan** [comment]
Is that first link what you intended?

**Comment by ddemidov** [comment]
It leads me to 'API Reference' page, so yes. The front page is here: http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/latest but its just a copy of the github README, so I thought I would skip it.

**Comment by WasabiFan** [comment]
Sorry, I wasn't very clear; I meant that the first link was to ev3dev-lang docs while the second was to the Python ones.

**Comment by ddemidov** [comment]
Oops, fixed the links. Thanks!
