### ISSUE TITLE
Include shebangs in example code

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#198]
We should make it a common practice to include shebangs in all the tutorials and examples so that people add them to their code every time they start a new program. That way, running them from Brickman will "just work" (aside from the executable bit issue).

**Comment by ndward** [comment]
Based on my experience (see the other issue) won't necessarily'just work' for Windows users?

**Comment by WasabiFan** [comment]
It will not make anything that works without a shebang stop working. Adding a shebang will allow you to run the code more easily on the brick, but to use those easier methods you may also have to use UNIX-style line endings. We can make a note of that when we add instructions to use shebangs.

**Comment by dwalton76** [comment]
I took a quick look through the demo directory and all of those have a shebang...which examples are missing them?

**Comment by WasabiFan** [comment]
It was mainly the README examples which I was considering; there wasn't anywhere that someone was told to add a shebang to their files. The README changes that were merged in earlier fix that in my eyes, so I think this can be closed unless there's anywhere else I am missing.
