### ISSUE TITLE
Elegant way of determining outputs?

### ISSUE THREAD

**Issue by antonvh** [rhempel/ev3dev-lang-python#2]
In the boostc lib there was a property OUTPUT_A, which would return 'outA' on an Ev3 but the literal /dev path on a Brickpi, something with TTY. What is an elegant way of filling this property on ev3dev?

**Comment by rhempel** [comment]
I'm not sure - what I do in my sample code is `m = Motor('outA')` and it "just works". You can always get the full path of the device like this `print( m.port_name )`

**Comment by antonvh** [comment]
I use this now, which works fine cross platform:
`m = Motor(name="motor0")`
