### ISSUE TITLE
driver_name is missing from device constructors

### ISSUE THREAD

**Issue by ddemidov** [rhempel/ev3dev-lang-python#215]
4a873844cdeff38ebc5d870f8c8bdfedefa2e8e3 removed filtering by `driver_name` attribute from device constructors. Example:

https://github.com/rhempel/ev3dev-lang-python/commit/4a873844cdeff38ebc5d870f8c8bdfedefa2e8e3?diff=split#diff-52ffd7ac54a3727e62910423b8b5a485L800

As a result, when there is single large motor and single medium motor connected to the system, the following script, without explicitly specifying output ports, is not guaranteed to pick correct devices:
```py
lm = LargeMotor()
mm = MediumMotor()
```

**Comment by WasabiFan** [comment]
Good catch! Glad we caught it before releasing anything.
