### ISSUE TITLE
Make use of polling functionality in 16-ev3dev kernel

### ISSUE THREAD

**Issue by ddemidov** [rhempel/ev3dev-lang-python#230]
Kernel Release Cycle 16 restores support for polling the `status` attribute of the tacho motor class for EV3 (see ev3dev/ev3dev.github.io#284). This may be used to wait for changes in motor state efficiently, so we should provide an interface for this feature.

**Comment by ddemidov** [comment]
Something like
```py
motor.wait_while('running') # wait while `'running'` is in the motor's `state`.
motor.wait_until('holding') # wait until `'holding'` is in the motor's state
```
should be doable.

**Comment by WasabiFan** [comment]
Keep in mind that we'll need to account for race conditions. I don't believe we're guaranteed that the state will change to "running" immediately.

**Comment by ddemidov** [comment]
I am not sure I understand. I was thinking of something along these lines:
```py
class Motor:

  def wait(self, is_done):
    while True:
      wait_for_polling_event()
      if is_done(self.state): break

  def wait_while(self, s):
    self.wait(lambda state: return s not in state)
```
Would that be more error prone that what we have to do currently (`while 'running' in m.state: sleep(0.01)`)? Or do you say that polling event could come later that that state has actually changed?

**Comment by WasabiFan** [comment]
No, it's not more error-prone than the loops we currently use; however now that we are building it into the library itself we need to make sure it's not going to fail on edge cases.
