### ISSUE TITLE
Can't turn up LED brightness: 'Led' object has no attribute '_path'

### ISSUE THREAD

**Issue by DanielPBak** [rhempel/ev3dev-lang-python#232]
- **ev3dev version:** 4.4.24-16-ev3dev-ev3
- **ev3dev-lang-python version:** Most modern version

I'm trying to get an LED plugged into the B port to turn on. When I do, I get the error below. How can I fix this?

``` python
import ev3dev.ev3 as ev3
import numpy as numpy
import time as timer
m = ev3.LargeMotor('outA')
light = ev3.Led('outB')
light.brightness = 10
time = numpy.random.normal(loc=5.0, scale=1.0, size=None)
time = time * 1000
speed = 180 / ( time / 1000 )
print time
print speed
print m.state
print "running first move"
m.run_timed(time_sp=time, speed_sp=speed)
while len(m.state) > 0:
    print m.state

timer.sleep(0.5)
m.polarity = 'inversed'

print "running the second move"
m.run_timed(time_sp=time, speed_sp=speed)
print m.state
while len(m.state) > 0:
    print m.state
```

```
robot@ev3dev:~$ python gaussian_motor.py 
Traceback (most recent call last):
  File "gaussian_motor.py", line 6, in <module>
    light.brightness = 10
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 1706, in brightness
    self.set_attr_int('brightness', value)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 210, in set_attr_int
    self._set_attribute(attribute, '{0:d}'.format(int(value)))
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 204, in _set_attribute
    self._attribute_cache.write(abspath(self._path + '/' + attribute), value)
AttributeError: 'Led' object has no attribute '_path'
```

**Comment by WasabiFan** [comment]
> Most modern version

In the future, please include the actual version number; in this case, you aren't actually using the "most modern version".

Recent releases of the library only support Python 3, whereas you are running your code as Python 2 (the `python` command is the Python 2 runtime). So, by running your code with `python`, you are actually picking up a very old version of this library which won't work on that kernel. To fix the problem, either switch to running it with the `python3` command or set up your file [as explained in the README](https://github.com/rhempel/ev3dev-lang-python#writing-python-programs-for-ev3dev).

**Comment by WasabiFan** [comment]
Did the solution that I described above work, or were other issues encountered? If this was resolved, it would be helpful to close the issue so that we know that there isn't anything more that we should be looking in to.

**Comment by dlech** [comment]
You need to put the port in `led` mode. http://www.ev3dev.org/docs/ports/legoev3-output-port/

You can either do this via the Device Browser on the brick or you can do it programmatically in python.

You will have to check `ls /sys/class/leds/` to see what the device name is.`'outB'` in `ev3.Led('outB')` is probably wrong.

**Comment by WasabiFan** [comment]
> You need to put the port in led mode

Although this is an issue, @DanielPBak needs to switch to running code against the Python 3 version of the library otherwise nothing else will function properly. I realized that there would be more issues with the LED port configuration after re-reading the question earlier today, but I want to make sure that he gets the larger environment set up correctly before continuing along the current path.

**Comment by ddemidov** [comment]
Can this be closed?

**Comment by dwalton76** [comment]
```Leds.set_color(Leds.LEFT, Leds.AMBER)```, etc work so I am going to close this one, we can re-open if the submitter is still seeing an issue.
