### ISSUE TITLE
LargeMotor has no attribute _path

### ISSUE THREAD

**Issue by Fuzzyma** [rhempel/ev3dev-lang-python#238]
- 4.4.19-15-ev3dev-ev3
- **ev3dev-lang-python version:** How do I get this?

I am not exactly sure, why this is happening now, but when I execute simple code, I always get:

```
Exception AttributeError: "'LargeMotor' object has no attribute '_path'" in <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0xb6c1c850>> ignored
```

That ofc happens only when the object is garbage collected. The thing is, that this goes hand in hand with my motors not connected.

I can reproduce this error by running in the interactive python shell:

```py
from ev3dev.ev3 import LargeMotor

# some nonexistend motor
a = LargeMotor('asdsad')
a.connected  # False
a = 2 # Error from Garbage collection see above
```

And when I run this code, noone of my motors is connected even when they connect in the intearctive python shell:

```py
motos = {}
for port in 'ABCD':
    motors[port] = LargeMotor(address='out' + port)
    if not motors[port].connected:
        print "No Motor at port", port
```

That outputs
```
No Motor at port A
No Motor at port B
No Motor at port C
No Motor at port D
```

Could be related to #96. However: I am a bit lost her. Any help is appreciated!

**Comment by ddemidov** [comment]
It looks like you are using version 0.6.0 of the bindings, because in the recent versions motors no longer have destructors. 0.6.0 is no longer supported (but may be picked up if you are using python2). Can you try to run these examples with python3?

**Comment by WasabiFan** [comment]
To explain a bit, the library now only supports Python 3. If you run your code with Python 2, it will actually be using an old version of the library (the last one which was compatible with Python 2), which doesn't work on this OS version. Running it with Python 3 should work.

**Comment by Fuzzyma** [comment]
Indeed - this is not printing that ugly exception anymore.
However: All my motors are not connected when I run my script with:

```
from ev3dev.ev3 import LargeMotor
motors = {}
for port in 'ABCD':
    motors[port] = LargeMotor(address='out' + port)
    if not motors[port].connected:
        print("No Motor at port", port)
```

I get output saying that no motor is connected.

When I run exactly the same code in the interactive python shell it is working as expected.
Anyone knows what the difference is?

**Comment by ddemidov** [comment]
Can you try that without 'address=' bit? Address should be the first non - keyword argument.

**Comment by Fuzzyma** [comment]
The problem was - as always - me. I passed `arkws` to the constructor (which are empty). That for some reason made it fail. So my issue is solved for now (even if I dont understand why `LargeMotor('out' + port, **kwargs)` does not work)

**Comment by ddemidov** [comment]
The following works for me when launched as a script:
```py
#!/usr/bin/env python3

import ev3dev.ev3 as ev3

def get_motor(**kwargs):
    return ev3.LargeMotor(**kwargs)

for m in [get_motor(address='out' + p) for p in 'ABCD']:
    if m.connected:
        print(m.address)
```

**Comment by ddemidov** [comment]
This works as well, so not sure what could be the problem:
```py
#!/usr/bin/env python3

import ev3dev.ev3 as ev3

def get_motor(address, **kwargs):
    return ev3.LargeMotor(address, **kwargs)

for m in [get_motor(address='out' + p) for p in 'ABCD']:
    if m.connected:
        print(m.address)
```

**Comment by Fuzzyma** [comment]
Mh - for some reason it doenst work... well - not ciritical for me atm. Its surely a mistake on my side so this can be closed
