### ISSUE TITLE
updating python not working

### ISSUE THREAD

**Issue by peterpedro** [rhempel/ev3dev-lang-python#251]
Good evening. I'm trying to update my system and install python 0.8.0, but apt-get update gives me the following message:

"The following packages were automatically installed and are no longer required:
  python-bluez python-dbus python-dbus-dev python-ev3dev python-pil
Use 'apt-get autoremove' to remove them."

Of course I didn't...
My system is:
uname -r
4.4.24-16-ev3dev-ev3
apt-cache show python-ev3dev | grep Version
Version: 0.6.0

Thank you in advance
Regards

Pedro

**Comment by ddemidov** [comment]
Those are all python2 packages which are no longer required since the library is now only supports python3. The package is called `python3-ev3dev`.

**Comment by peterpedro** [comment]
Yes, I have checked the installed packages and realized there were python, python2.7, python3...
Thank you so much for your superfast help
Best regards
