### ISSUE TITLE
Beginner help wanted to setup Atom and more

### ISSUE THREAD

**Issue by romainschmid** [rhempel/ev3dev-lang-python#256]
Hi, 

I am not sure wether I should write here, but I have to try !

I've discovered ev3 python very recently. I was looking for some way to write code instead of using the classic Mindstorms GUI app.

I must say first that I am a total newbie, but I know a few things. 

I've already installed the ev3dev on my robot, and connected it via Bluetooth, I have even been able to shut it down with Terminal (I'm on a mac). Cool. 
I am currently trying to learn python with https://learnpythonthehardway.org/ and the author recommends Atom to write code instead of PyCharm or any other IDLE/IDE. 
I've read the github discussions about the doc not being very clear for beginners. I've also read some other things on the web, and I can't find the way to get Atom (atom.io) aware of all the ev3python library and classes (sorry if I say stupid things, I still have quite a lot to learn !)

If I try and sum things up :
ev3dev is installed and runs, my robot boots correctly, I can SSH it, and I need help to figure out how to be able to write code in an editor with the classes. Does it make sense ?

Thanks for any help, and a big thank you for giving us the opportunity to get a little cleverer (hopefully)

Romain

**Comment by ddemidov** [comment]
Did you have a look at https://ev3python.org?

**Comment by romainschmid** [comment]
Hi, 

Thanks for the reply. Yes, I have read it. The thing is, I am a bit confused, because I've read so many things lately, I've tried many, and sometimes I go through some web page explaining this or that, and I don't really understand. 
What I currently can't figure out is how to install/use this ev3dev-lang-python. Do I even need it ? You must be smiling reading this !

**Comment by ddemidov** [comment]
It should be already pre-installed of you flashed with a recent image. To check this, ssh to your ev3, and do this in terminal:

```
python3
```
This should open an interactive python session. There enter 
```py
from ev3dev.ev3 import *
Sound.speak('hello')
```
Press ctrl-d on an empty line to exit.

**Comment by ddemidov** [comment]
I would recommend reading this page as a next step: https://sites.google.com/site/ev3python/putty

**Comment by romainschmid** [comment]
Yes, it works. I've found this
https://www.gitbook.com/read/book/7hal32/ev3-tud-main/chapters/ev3dev-TUD/setup.html
but
it's finally a 404 error. The text below that google search was interesting
:
By default there will only be auto-completion for standard Python packages.
To enable it you will have to install the ev3dev languages bindings for
Python. +.
I've been able to see this website, and I've seen some interesting code on
it in order to be able to do what I'd like to, but it was at school, and
now, for some reason, I can't access it anymore.
As you have already guessed, it's a bit messy in my head, I can't even ask
the right question ! But I will finally figure it out...
-- 
Romain Schmid
Chemin Henri-Giroud 7
1446 Baulmes
079/249 24 48

**Comment by romainschmid** [comment]
Aaaaaah, finally ! 
I had to update pip, install Pillow, and I finally managed to get the code properly highlighted and all classes included in PyCharm. But what a hassle !
I'd say you can close after a nice little beer. Thanks for your patience.

**Comment by ddemidov** [comment]
:beers:
