### ISSUE TITLE
sound volume not doing anything?

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#258]
- **ev3dev version:** 4.4.19-15-ev3dev-ev3
- **ev3dev-lang-python version:** 0.8.0

``` python
from ev3dev import ev3
for v in range(0,100,10):
  ev3.Sound.volume = v
  ev3.Sound.tone(400, 50)
```
https://github.com/ev3dev/ev3dev/wiki/Using-Sound#sysfs-attributes-and-module-parameters

This probably came from the transition to use the beep command, which does not have a volume parameter.

Should we shell out the same way and call, e.g.
```
amixer -q set Playback 50%
```

**Comment by ddemidov** [comment]
Currently `Sound` is just a convenience class that wraps `espeak`, `aplay` and `beep` utilities. It does not inherit from `Device`, so `Sound.volume = v` does nothing except for creating a class level field named `volume`.

Did you try writing to `/sys/devices/platform/snd-legoev3/volume` directly? Does that work? In case it does, we could easily introduce the volume attribute to the `Sound` class.

**Comment by dlech** [comment]
FYI, I don't intend to keep `/sys/devices/platform/snd-legoev3/volume` around forever, so I would not suggest becoming reliant on it. Better to use the ALSA mixer instead.

**Comment by ensonic** [comment]
yep, this works too:

     echo "10" | sudo tee /sys/devices/platform/snd-legoev3/volume

I thought using amixer would be more portable to e.g. brickpi. But on the other hand writing to the sysfs is probably faster than spawning a binary.
I am bringing this up, because this worked in the past before we switched to the beep command.

**Comment by dlech** [comment]
There is also [python-pyalsa](https://packages.debian.org/jessie/python-pyalsa) and [python-alsaaudio](https://packages.debian.org/jessie/python-alsaaudio) but these don't have python3 packages.

**Comment by ddemidov** [comment]
See #259
