### ISSUE TITLE
Fonts module throws unhandled error when invalid font name supplied

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#260]
- **ev3dev version:** `4.4.19-15-ev3dev-ev3`
- **ev3dev-lang-python version:** 0.8.0

When an invalid font name is requested (as seen below after I mistyped the font name), it throws an error as a result of attempting to access a nonexistent file.

```
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    font = fonts.load('luB14')
  File "/usr/lib/python3/dist-packages/ev3dev/fonts/__init__.py", line 24, in load
    return ImageFont.load(pil_file)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 205, in load
    f._load_pilfont(filename)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 72, in _load_pilfont
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/ev3dev/fonts/luB14.pil'
```

**Comment by ddemidov** [comment]
What is the desired behavior here? Load a default font (with a warning), or throw exception with a more user-friendly message?

**Comment by WasabiFan** [comment]
I'd say it should just catch the error and throw a more friendly one.  From looking at this, it is hard to tell what actually went wrong; if we still force the user to deal with it but tell them what they need to fix, it should be fine.
