### ISSUE TITLE
changing motor speeds while running is done differently for regulated and unregulated

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#263]
- **ev3dev version:** 4.4.19-15-ev3dev-ev3
- **ev3dev-lang-python version:** 0.8.0

When changing motor-speed for unregulated mode I can just change duty_cycle_sp and the motor speed changes. For regulated mode setting speed_sp does not have any effect. I am sure this worked before, I was using this in open roberta to provide a fast way to adjust speed.

Example code on: https://gist.github.com/ensonic/bcb0e15b9c9b94cf99bc47b2d6a7c1d7

**Comment by ddemidov** [comment]
I think this is a documented behavior (run-direct section here: http://www.ev3dev.org/docs/tutorials/tacho-motors/).

**Comment by WasabiFan** [comment]
Speed regulation mode was removed in the 10-ev3dev kernel. Everything now behaves as if regulation were on except the `run-direct` mode. Also, changing `speed_sp` has no effect after the command has started; you need to use unregulated `run-direct` for that. I don't believe that that behavior has ever changed.

**Comment by ensonic** [comment]
Okay, let me remove all the 'speed_regulation_enabled' attribute usage then.

Still why is it asymmetric? Calling run_forever() will do more work then just changing the speed, right?

**Comment by ensonic** [comment]
Can anyone answer the last question? I'll retry if this is still the case though.

**Comment by dlech** [comment]
It depends on the motor controller. Some controllers are on I2C or UART or SPI, so all information on the motor command has to be sent at once. `run-direct` may or may not work on these controllers. On EV3, `run_forever()` should not be much more overhead than an extra `seek` and `write`.
