### ISSUE TITLE
Installing library on a desktop PC: can we ensure that running code won't accidentally mess with the system?

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#265]
If you want autocomplete in an IDE on a desktop PC, you can install the package (with `pip` or `apt`). However, I believe that this opens up the potential for creating odd files in unpredictable places if you accidentally run your code on the desktop PC: on Linux, it'll probably throw an error, but on Windows/macOS I really can't say what will happen. How might we be able to mitigate this issue? I think the simplest approach would probably be to add a check to confirm that it's running on-robot.

**Comment by ddemidov** [comment]
You would probably get an error on each of the platforms. The library should only attempt to write anything if a device was successfully connected, and that should not happen.

> I think the simplest approach would probably be to add a check to confirm that it's running

I did not understand this. What should be running?

**Comment by WasabiFan** [comment]
We have setters which, due to the nature of Python, could be invoked by a user in a way that would bypass device connection. Doing so wouldn't even be against general good practice in Python for the most part. So, I'm thinking that we should add a check just like we already have for the Python version which targets the OS and/or some other ev3dev attribute.

**Comment by ddemidov** [comment]
We check that device is connected before attempting to set an attribute: https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/core.py#L208

**Comment by WasabiFan** [comment]
Hmmm... I hadn't considered that. It's still possible for someone to bypass the check, but it's fairly unlikely for a normal user.
