### ISSUE TITLE
Move HTTP code in helper.py to a separate file

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#269]
A basic python3 hello_world.py program that imports helper.py takes about 19s to run on my EV3.  Some digging shows that a large chunk of this time is spent in "from http.server import BaseHTTPRequestHandler, HTTPServer".  I moved all of the HTTP code in helper.py to a www.py and my hello_world.py now runs in 9s.

9s still seems like too long but it is a lot better than 19s.  Does www.py sound ok?

**Comment by WasabiFan** [comment]
I'm not sure that "www.py" is accurate as a name; it isn't actually World Wide Web code, it's an HTTP server intended to be used locally. I'd prefer something like "web-server.py". Good changes otherwise.

**Comment by dwalton76** [comment]
Will do webserver.py (dashes in filenames are problematic when importing)
