### ISSUE TITLE
Remove kociemba and rubiks_rgb_solver.py from MINDCUB3R demo

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#270]
I forked kociemba (sent a pull request to make it python3 compatible) and created a repo for the rubiks cube RGB analyzing code.  We can now remove these from demo/MINDCUB3R and instead point the user to install them via:
```
sudo apt-get install build-essential python3-pip
sudo pip3 install git+https://github.com/dwalton76/kociemba.git
sudo pip3 install git+https://github.com/dwalton76/rubiks-color-resolver.git
```

@WasabiFan @ddemidov sound good?

**Comment by WasabiFan** [comment]
Sounds good to me!
