### ISSUE TITLE
Cover demo programs in primary README

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#273]
A starting point for a section to add to the main README to let users know how to install and run the demo programs

Demo Programs
-------------
There are several [demo programs](https://github.com/rhempel/ev3dev-lang-python/tree/master/demo) that you can use as references for programming your own robot in python on ev3dev. To install these on your EV3, use git to clone the ev3dev-lang-python repository.
```
$ sudo apt-get install git
$ git clone https://github.com/rhempel/ev3dev-lang-python.git
```

To run one of the demo programs from the command line, cd to the directory and run the program via `./PROGRAM_NAME.py`.  Example:
```
$ cd ev3dev-lang-python/demo/R3PTAR/
$ ./r3ptar.py
```

You can also run a demo program via Brickman by selecting the program in the File Browser.  Note that for both running from the command line and running from Brickman the program must be marked as an executable and the first line of the program must be `#!/usr/bin/env python3`.  To mark a program as executable run `chmod +x PROGRAM_NAME.py`.  All of the demo programs are already marked as executable and already have `#!/usr/bin/env python3` so you should be fine, we only mention it so you know to do these things when writing your own programs.

**Comment by WasabiFan** [comment]
I think that this should be two separate sections: one for demos specifically and one for your own programs. It would make sense if the former were in the README in the demo folder.

**Comment by dwalton76** [comment]
What if we take the text above and put it in demo/README but also add the following to the primary README

### Running programs
When you write your own program there are two important steps you must take for the program to work:
- The first line must be `#!/usr/bin/env python3`
- The program must be executable. To mark a program as executable run `chmod +x PROGRAM_NAME.py`

You can then run PROGRAM_NAME.py via the Brickman File Browser or you can run it from the command line via `$ ./PROGRAM_NAME.py.`

**Comment by ensonic** [comment]
I think we should just make sure that all demos have ```#!/usr/bin/env python3``` and also that the have the execute bit set in git.

**Comment by WasabiFan** [comment]
@ensonic the problem is that having it marked in git doesn't necessarily mean that it will keep it's state once a user transfers the file to the brick. Remember, many people will just download these files via the web interface.

**Comment by dwalton76** [comment]
Currently all of the demo programs have `#!/usr/bin/env python3` and all except EV3RSTORM/ev3rstorm.py are executable.  I'll fix that via the pull request to update the READMEs.

**Comment by ensonic** [comment]
What it we add a fix in brickman to make text files starting with a she-bang executable (if they aren't)?

**Comment by WasabiFan** [comment]
ev3dev/ev3dev#737
