### ISSUE TITLE
Holiday Hackathon?

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#275]
Given that christmas is coming up and folks either have some time off or are visiting family and need something to do to escape their family for a few hours...any interest in doing an ev3dev-lang-python hackathon?

Brainstorming some project ideas that we could probably collectively do in < 24 hours (or we do a 12 hour hackathon if that is more manageable):
- port the odometry library in #235 
- build some more of the EV3 reference models and add them to the demos
- this wouldn't contribute much to the core of the repo here but it would be fun...I've been thinking about building a robot that could play the NES version of Tetris.  The game would run on a laptop, raspberry pi, etc with a keyboard attached.  You position a color sensor over the part of the screen where is shows you what the "next" piece is and then you have the motors press the appropriate keys to turn, shift, and drop the block.  The only gotcha might be learning what the very first piece is, I'm not sure if that shows up in the "next" block or if it just starts dropping down from the top as soon as you start.  Maybe the user has to tell us what the first piece is.

What do you guys/gals think?

**Comment by WasabiFan** [comment]
I'm in -- my plan is to do as much ev3dev-related work as possible, so this is definitely something that's interesting to me! One of the topics that I've been thinking of is #264 (an ev3dev simulator).

**Comment by dwalton76** [comment]
That would be cool....do you think we could pull that off in a hackathon? What simulator do you think we should build on? Some of the ones in that thread look down right amazing.

**Comment by WasabiFan** [comment]
If we want to pursue it we can discuss over in that issue; I think the main task is to essentially implement the ev3dev motor drivers at some level to back a simulation environment. The actual simulation could be anything from a simple 2D rendering of a robot to a full 3D physics-based one... for these purposes (a short hackathon-style time range) we'd probably want to go with the former, at least as a starting point.

As to the logistics of such a thing, what are you imagining? Create a Gitter room to use and set a date/time?

**Comment by dwalton76** [comment]
Was researching the Tetris idea, not surprisingly there is some good Tetris AI code out there:
https://codemyroad.wordpress.com/2013/04/14/tetris-ai-the-near-perfect-player/

**Comment by dwalton76** [comment]
Yeah I figure we pick a date, figure out how long we want it to be, pick a project, create a branch here, maybe kick it off with a video conference and then chat via Gitter after that.

**Comment by WasabiFan** [comment]
Sounds good to me! Maybe we should advertise this somewhere that other ev3dev community members (who aren't watching this repo) could find it... what do you think?

**Comment by dwalton76** [comment]
yep, let's pick a date/time first and then we can send it out.  How about Dec 30th?  We could start at noon EST that way it isn't crazy early for anyone on the west coast (I realize now I have no idea where any of you guys live and what timezones you might be in).

Something else to settle on before we announce is how long this will be.  My vote would be for either 12 hours or 24 hours....I could do 24 hours given enough coffee.

Most hackathons have some sort of prize but that involves a lot of hassle (buying/shipping the prizes, judges, etc), my vote would be to not bother with prizes just to simply things.

**Comment by WasabiFan** [comment]
I have some troublesome travel plans that I wanted to nail down before saying anything definitive; now that I know when I'm going to be unavailable I can actually help with specifics. I'm going to be traveling on the 19th, the 25th and the 30th, and likely will be unavailable in general between the latter two dates :laughing:... I can't say that leaves much in the way of flexibility 😢 I'll be in UTC-5 for most of that.

I agree on all points; 12 hours is the most reasonable and more than basic arrangements are probably more than necessary. We should just get a few people and have some fun doing cool projects.

**Comment by dwalton76** [comment]
Maybe we should aim to do it sometime in Feb so that folks have time to plan ahead?

**Comment by WasabiFan** [comment]
Yeah, that sounds good to me! I am not sure of exactly when we may want to schedule it though.

**Comment by dwalton76** [comment]
https://github.com/ev3dev/ev3dev/issues/92 "Daisy chaining two EV3s?" might be a good hackathon project

**Comment by dwalton76** [comment]
Am going to close this...we can re-open if we get motivated enough to do a hack-a-thon
