### ISSUE TITLE
ev3dev + rpi3 + brickpi + python - how to setup ?

### ISSUE THREAD

**Issue by MikeDabrowski** [rhempel/ev3dev-lang-python#279]
- **ev3dev version:** none
- **ev3dev-lang-python version:** none
- **python version** 2.7.6 and 3.4

I want to use ev3dev library on rpi3 and brickpi setup. I can't find any tutorial though. I do not have ev3 brick, just rpi3 and brickpi. Last month I tried to flash sd with image from ev3dev main site but for some reasons it couldn't boot so I abandoned it and focused on brickpi solutions. That solutions are completely unusable so I'm back to ev3dev. 

Is it possible to use raspbian for robots and somehow install ev3dev library for python on my rpi3? If yes then how?

**Comment by dlech** [comment]
Did you edit `config.txt` on the SD card before booting? You have to enable BrickPi there and there are some special considerations for RPi 3 since the Bluetooth tries to use the same UART/serial port as the BrickPi by default.

**Comment by dlech** [comment]
> Is it possible to use raspbian for robots and somehow install ev3dev library for python on my rpi3?

You could, but it won't work because the ev3dev python library requires a hardware driver. If you are comfortable with compiling the driver (and possibly your own device tree) you could in theory make ev3dev stuff work using Raspbian for Robots.

**Comment by MikeDabrowski** [comment]
Would it boot without configuring config.txt? I can't remember modifying that file. I don't and won't need bluetooth for my robot. Guess I'm gonna need to start again. Will following tutorial on http://www.ev3dev.org/docs/getting-started/ suffice? I can't quite grasp what ev3dev actually is - ev3 system or it also works on rpi?

**Comment by dlech** [comment]
> Would it boot without configuring config.txt?

It would boot, but you could not use the BrickPi.

> Will following tutorial on http://www.ev3dev.org/docs/getting-started/ suffice?

Yes, it should. Be sure to look for the info/warning boxes about Raspberry Pi.



> I can't quite grasp what ev3dev actually is - ev3 system or it also works on rpi?

It is a Debian Linux based operating system for LEGO MINDSTORMS and LEGO MINDSTORMS compatible devices. Since BrickPi and PiStorms are LEGO compatible, we have a Raspberry Pi version of the OS and there is also a BeagleBone cape called the EVB that is LEGO compatible, so we have a BeagleBone version of the OS.

**Comment by MikeDabrowski** [comment]
> It would boot, but you could not use the BrickPi.
Then I must've done something else wrong. Mine didn't boot at all. Stuck in the middle. I'm finishing flash right now and will test it

**Comment by MikeDabrowski** [comment]
It is booting almost 25minutes. Stuck on "Started Update UTMP about system runlevel changes" Green activity led is blinking. Two BrickPi blue led's are on. I have modified config.txt. Disabled BT (left commented) and enabled brickpi

**Comment by dlech** [comment]
The blue lights are a good sign. Have you tried making a network connection with ssh? I've never actually used and HDMI display with RPi, so I don't know what to expect there.

**Comment by MikeDabrowski** [comment]
I'm afraid ssh wont work. I had fail on setting up network connection (wifi password not set for wpa suppl.) After 2h it is still in the same state. I will reflash using another tool and try again. Etcher said my card may be corrupted...

**Comment by MikeDabrowski** [comment]
:) reflashed, botted and still stucks on UTMP

**Comment by dlech** [comment]
> Etcher said my card may be corrupted...

It is probably right. Do you have another card to try?

**Comment by MikeDabrowski** [comment]
I sacrificed other card for that. Etcher said its ok.
And uncommented this lines:
dtoverlay=brickpi
init_uart_clock=32000000
dtoverlay=pi3-disable-bt

Do I need to plug Ethernet cord ? Or should I place my wifi password somewhere on the card so it could load it during boot? Bit weird but maybe it will help.
Well so far 2minutes stuck on UTMP

**Comment by dlech** [comment]
> Do I need to plug Ethernet cord ?

Yes, that is the best way to attach to start with.

> Or should I place my wifi password somewhere on the card so it could load it during boot?

There is not currently a way to do this with ev3dev.

> Well so far 2minutes stuck on UTMP

The Pi 3 boots in about 5 seconds, so no need to wait this long. I'm not really sure that it is stuck. Try ssh via Ethernet or press ALT+CTRL+F6 to try a different console.

**Comment by MikeDabrowski** [comment]
Connectinv ethernet didnt help but after switching to console f6 i got logging screen

**Comment by dlech** [comment]
OK, so you can log in as `robot` password `maker` and setup wifi with `connmanctl`.

**Comment by dlech** [comment]
> Connectinv ethernet didnt help

If your host computer is Windows, using hostname of `ev3dev` should work. on Mac/Linux `ssh ev3dev.local` should connect.

**Comment by MikeDabrowski** [comment]
Okay, I managed to do this all. I've set up /var/lib/connman/wifi.config to autoconnect to wifi at boot. Dont know if that works yet. Now I will try if nxt stuff works with python.

**Comment by MikeDabrowski** [comment]
Huh so... running example led or motor from [here](https://media.readthedocs.org/pdf/python-ev3dev/latest/python-ev3dev.pdf) gets me "device not connected" . And after rebooting and plugging in battery pack motors connected to B and C run continuously

**Comment by dlech** [comment]
BrickPi motors will not run without using the BrickPi power connector. That is to say, back-powering the BrickPi from the RPi via USB or some other means is not supported. It sounds like the script work (at least partly) and left the motors running, which didn't actually start until you powered them.

Also, please post your code if you would like more help with it.

**Comment by MikeDabrowski** [comment]
Nxt motors connected to brick pi connected to rpi will only work if i power up brickpi with battery pack. Let me clarify: After first boot I opened python console and tried to run motor b. Didn't work (device not connected) after that I noticed I switched off battery so I switched it on. Script was not running and I was out of python console amd motors (both ) were running non stop. So I rebooted and switched battery on. Still running continuously. I will paste that script on Monday but it is described I that link I gave in previous post. I used python 3

**Comment by MikeDabrowski** [comment]
LED.py:
```
import ev3dev.ev3 as ev3
ts = ev3.TouchSensor()
while True:
        ev3.Leds.set_color(ev3.Leds.LEFT, (ev3.Leds.GREEN, ev3.Leds.RED)[ts.value()])
```

motor.py:
```
import ev3dev.ev3 as ev3
m = ev3.LargeMotor('outB')
m.run_timed(time_sp=3000, speed_sp=500)
```
Files are located in home directory /home/robot
Few seconds after powering on brickPi (with battery on) motors start tor run. I can't ssh before that point, nor run any script.

**Comment by ddemidov** [comment]
When you are on brickpi, you should `import ev3dev.brickpi as ev3`. BrickPI and EV3 have different leds and input/output port address names.

**Comment by MikeDabrowski** [comment]
Okay, but why motors start to run on boot?

**Comment by ddemidov** [comment]
Sorry, that I have no idea about :sheep:

**Comment by MikeDabrowski** [comment]
I just reflashed card and booted it up with battery power on. I got few lines like this, which I've not seen before:
`lego-port port1: Registered 'ttyAMA0:S2' on 'ttyAMA0' `

But motors still run cont.

**Comment by MikeDabrowski** [comment]
I also got "Started BrickPi Line Discipline" is that predefined program ? Maybe that is why it turns motors?

**Comment by dlech** [comment]
> "Started BrickPi Line Discipline"

This is the ev3dev hardware driver for BrickPi, so this message is expected.

I'm not sure why the motors would be running continuously at boot though. Please open an new issue at https://github.com/ev3dev/ev3dev/issues and list the exact model of Raspberry Pi and BrickPi you are using as well as the image file that your are using and I will try to reproduce the problem.

If you are not completely removing all power when you reboot, I imagine that the BrickPi is not being rebooted and it is in a bad state when the Raspberry Pi is rebooted.
