### ISSUE TITLE
BrickPi Python add one and more sensors

### ISSUE THREAD

**Issue by MikeDabrowski** [rhempel/ev3dev-lang-python#280]
### System information:

* I am using: 
  - RaspberryPi  3 Model B v1.2
  - BrickPi (old model (maybe HW v1.7.3) but FW upgraded to 2.0)
  - NXT motors and sensors
  - EV3 gyro sensor 

* I installed ev3dev using this image file: *ev3dev-jessie-rpi2-generic-2016-12-21.img*

* My kernel version is: *4.4.32-17-ev3dev-rpi2*

* My host computer is running: *Windows10 pro*

* My IDE: *PyCharm 2016.3

* I am connecting using: *wifi*

* My changes to config.txt (only enabled options):*
```
dtoverlay=brickpi
init_uart_clock=32000000
dtparam=brickpi_battery=okay
dtoverlay=pi3-disable-bt
dtparam=brickpi_led1_trigger=none,brickpi_led2_trigger=none
```

### About my issue:
BrickPi does not auto detect sensors so they need to be set up manually. To do that one can use those commands:
```
$ echo nxt-analog > /sys/class/lego-port/port0/mode
$ echo lego-nxt-touch > /sys/class/lego-port/port0/set_device
```
But it needs to be ran from shell and I only managed to successfully set one sensor.

### How to add one and more sensors in python?
I tried :
```
$ python3
>>> p = Device('lego-port', name_pattern='*', address='in4') 
``` 
But my python3 does not recognize `Device`

**Comment by WasabiFan** [comment]
It should be like this, although I can't test it right now:

```python
p = LegoPort(INPUT_1)
p.mode = "nxt-analog"
p.set_device = "lego-nxt-touch"
```

The documentation for that class is here: <http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/latest/other.html#lego-port>

**Comment by MikeDabrowski** [comment]
Are you sure to use both mode and set_device? Because I read in some other issue that this causes sensor0 to be set when `mode` is executed and then removed and sensor1 created when `set_device` is executed.

**Comment by WasabiFan** [comment]
Sorry, I just transcribed the script you gave into Python; I don't use a BrickPi so I am not exactly sure what must be set. I'd guess it is just `set_device`.

**Comment by dlech** [comment]
> Are you sure to use both mode and set_device?

Yes.


> Because I read in some other issue that this causes sensor0 to be set when mode is executed and then removed and sensor1 created when set_device is executed.

This is normal and not a problem.

**Comment by MikeDabrowski** [comment]
OK, I tested that and it worked.
For one touch sensor on port 1 of brickpi:
```
import ev3dev.brickpi as ev3

p = ev3.LegoPort(ev3.INPUT_1)
p.mode = "nxt-analog"
p.set_device = "lego-nxt-touch"

ts = ev3.TouchSensor(ev3.INPUT_1)
m=ev3.LargeMotor(ev3.OUTPUT_B)
m2=ev3.LargeMotor(ev3.OUTPUT_C)

while not ts.value():
	m.run_timed(time_sp=100, speed_sp=500)
	m2.run_timed(time_sp=100, speed_sp=500)
```
`ev3` needs to be before `LegoPort` and both `mode` and `set_device` have to be used

For two touch sensors on ports 1 and 2 of brickpi:
```
import ev3dev.brickpi as ev3

p = ev3.LegoPort(ev3.INPUT_1)
p2 = ev3.LegoPort(ev3.INPUT_4)
p.mode = "nxt-analog"
p2.mode = "nxt-analog"
p.set_device = "lego-nxt-touch"
p2.set_device = "lego-nxt-touch"


ts = ev3.TouchSensor(ev3.INPUT_1)
ts2 = ev3.TouchSensor(ev3.INPUT_4)
m=ev3.LargeMotor(ev3.OUTPUT_B)
m2=ev3.LargeMotor(ev3.OUTPUT_C)

while not (ts.value() or ts2.value()):
	m.run_timed(time_sp=100, speed_sp=500)
	m2.run_timed(time_sp=100, speed_sp=500)
```

**Comment by MikeDabrowski** [comment]
Should I use `mode` and `set_device` once per boot or leave that code each time I run my program?

**Comment by dlech** [comment]
I would leave it in the program.

**Comment by coffeedood** [comment]
I still keep getting this error.

>>> from ev3dev.brickpi3 import *
>>> import ev3dev.brickpi as ev3
>>> p = LegoPort(INPUT_1)
>>> p.mode = "nxt-analog"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3062, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: LegoPort(spi0.1:S1) is not connected
