### ISSUE TITLE
BrickPi python + gyroSensor

### ISSUE THREAD

**Issue by MikeDabrowski** [rhempel/ev3dev-lang-python#281]
### System information:

* I am using: 
  - RaspberryPi  3 Model B v1.2
  - BrickPi (old model (maybe HW v1.7.3) but FW upgraded to 2.0)
  - NXT motors and sensors
  - EV3 gyro sensor 

* I installed ev3dev using this image file: *ev3dev-jessie-rpi2-generic-2016-12-21.img*

* My kernel version is: *4.4.32-17-ev3dev-rpi2*

* My host computer is running: *Windows10 pro*

* My IDE: *PyCharm 2016.3

* I am connecting using: *wifi*

* My changes to config.txt (only enabled options):*
```
dtoverlay=brickpi
init_uart_clock=32000000
dtparam=brickpi_battery=okay
dtoverlay=pi3-disable-bt
dtparam=brickpi_led1_trigger=none,brickpi_led2_trigger=none
```
### My issue:
I tried to test gyroSensor:
```
import ev3dev.brickpi as ev3

p = ev3.LegoPort(ev3.INPUT_2)
p.mode = "ev3-uart"
p.set_device = "lego-ev3-gyro"

gs = ev3.GyroSensor(ev3.INPUT_2)

units = gs.units
while True:
	angle = gs.value()
	print(str(angle)+ " " + units)
```

This returns all 0 but sometimes I got random ones when shaking gyro.

**Comment by dwalton76** [comment]
Still an issue on latest kernel?

**Comment by MikeDabrowski** [comment]
I moved on with my life 😄 since then. I don't have time to check and I abandoned that project a year ago.
