### ISSUE TITLE
beacon proximity

### ISSUE THREAD

**Issue by urkarthiksg** [rhempel/ev3dev-lang-python#291]
4.4.32-17-ev3dev-ev3
Python 3.4.2

The EV3  IR sensor has a Proximity, Beacon detect (-25 to 25) and a Beacon Proximity.

the beacon proximity has a higher range than just IR proximity. is there a way to access the beacon proximity mode?

**Comment by ddemidov** [comment]
You should be able to put the sensor into `IR-SEEK` mode (http://www.ev3dev.org/docs/sensors/lego-ev3-infrared-sensor/) and use `value(1)` to get distance to beacon on channel 1:
```py
ir = InfraredSensor()
ir.mode = 'IR-SEEK'
print(ir.value(1)
```

**Comment by urkarthiksg** [comment]
Thanks. if i use the base software that comes from EV3, there is a Beacon Proximity mode that can detect a further distance (200cm or 79inch) -its also indicated their ev3 user guide..

I think when we do IR-SEEK, we still seem to be in the Proximity mode which is the 70cm / 27in case. so I was wondering if there was a way to get the 79in reach

**Comment by urkarthiksg** [comment]
another data point: if you look at port view, the IR-SEEK can only do smaller distances (27in). but if you open the EV3 Software from Lego and set the mode to Beacon Proximity, it can go to 79in.. so they must be doing some additional processing to extract this.

**Comment by ddemidov** [comment]
@dlech, do you have anything to say?

**Comment by dlech** [comment]
Our documentation on the website is incorrect. In IR-SEEK mode 100% is the same as the EV3-G software. The EV3 user manual says that this is about 200cm, however, I just measured it using the EV3-G software and found it to be about 110cm. I also measured it using the IR-SEEK mode in ev3dev and got the same result, so there is no difference between ev3dev and the official firmware that I can see.

**Comment by urkarthiksg** [comment]
Thanks David.  I am able to measure almost 78” for a 100% and able to see a similar value i can measure on the LegoEV3.

**Comment by dlech** [comment]
Cool. I must have some strange ambient light conditions that are affecting my reading.
