### ISSUE TITLE
Tag and release new version

### ISSUE THREAD

**Issue by ddemidov** [rhempel/ev3dev-lang-python#292]
We should release the updated debian package to be included into the upcoming image. Mostly because of #288. Do we need to do anything else before that?

**Comment by ensonic** [comment]
When using the develop version I get one issue:
```
Feb 02 13:35:31 ev3dev openrobertalab[11037]: Traceback (most recent call last):
Feb 02 13:35:31 ev3dev openrobertalab[11037]: File "/usr/lib/python3/dist-packages/roberta/lab.py", line 277, in _exec_code
Feb 02 13:35:31 ev3dev openrobertalab[11037]: exec(compiled_code, scope)
Feb 02 13:35:31 ev3dev openrobertalab[11037]: File "/home/robot/NEPOprog.py", line 36, in <module>
Feb 02 13:35:31 ev3dev openrobertalab[11037]: main()
Feb 02 13:35:31 ev3dev openrobertalab[11037]: File "/home/robot/NEPOprog.py", line 26, in main
Feb 02 13:35:31 ev3dev openrobertalab[11037]: run()
Feb 02 13:35:31 ev3dev openrobertalab[11037]: File "/home/robot/NEPOprog.py", line 21, in run
Feb 02 13:35:31 ev3dev openrobertalab[11037]: hal.driveDistance('C', 'B', False, 'foreward', 30, 20)
Feb 02 13:35:31 ev3dev openrobertalab[11037]: File "/usr/lib/python3/dist-packages/roberta/ev3.py", line 383, in driveDistance
Feb 02 13:35:32 ev3dev openrobertalab[11037]: ml.stop_command = 'brake'
Feb 02 13:35:32 ev3dev openrobertalab[11037]: AttributeError: 'NoneType' object has no attribute 'stop_command'
```
Here is the related code:
https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L382..L388

This shows that commit
4a85fd2 Error on non-existing arguments/parameters (#278)
is effective and that we did a bad job on communicating all the motor api changes. I'll release another openroberta update.

**Comment by ensonic** [comment]
Main issue why this release is breaking things (and we should communicate this well) is that I added two custom attributes to the motors:
https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L49..L50

and this now causes an exception. Will figure a hotfix, but this is meh :/

**Comment by ddemidov** [comment]
You could inherit from motor and add the attributes to the child.

**Comment by ensonic** [comment]
I have pushed fixes. Will also push another release now. Please mention this change in the RELEASE-NOTES though to make sure people are aware of it. Thanks. Everything else looks good. So thumbs up to release.

**Comment by WasabiFan** [comment]
I'm supportive of a release too. I don't have time do draft release notes ATM but should be able to tomorrow if it hasn't already been done.

**Comment by ddemidov** [comment]
I think I'll only have time for this tomorrow anyway.

**Comment by WasabiFan** [comment]
For reference, here's the diff since our last release: https://github.com/rhempel/ev3dev-lang-python/compare/master...develop

**Comment by ddemidov** [comment]
One can also go to [releases](https://github.com/rhempel/ev3dev-lang-python/releases) page and press 
the "[<n> commits](https://github.com/rhempel/ev3dev-lang-python/compare/0.8.0...develop) to develop" link there:
![screenshot from 2017-02-02 18-54-46](https://cloud.githubusercontent.com/assets/270503/22556650/f956b10e-e978-11e6-9abd-68a2d3c538f3.png)

**Comment by WasabiFan** [comment]
That's too much work :wink: I've just learned the URL for GitHub's compare page and typed it in; I used the `develop` branch while you used the release tag.

**Comment by DJuego** [comment]
Yes. Yes. Yesterday I started using ev3dev-lang-python in classes oriented to high school students. It worked well. 👍  I would like to take advantage of the latest improvements in ev3dev and the openroberta connector. A new updated debian package would be very welcome. Please. :-)

**Comment by ddemidov** [comment]
I've tagged 0.8.1 and pushed the packages to the server. I've also created a draft of the release notes [here](https://github.com/rhempel/ev3dev-lang-python/releases); @WasabiFan, could please check that out?

**Comment by WasabiFan** [comment]
That looks good; can you note the compatible kernel version and briefly explain the change relating to nonexistent properties? I'm on my phone right now and can't edit the release properly.

Thanks for doing that! I had hoped to find time earlier in the week but evidently failed.

**Comment by ddemidov** [comment]
Done.
