### ISSUE TITLE
List all sensors

### ISSUE THREAD

**Issue by craigsammisutherland** [rhempel/ev3dev-lang-python#293]
There is a function for listing all the attached motors, but nothing for listing the sensors. Based on list_motors, I came up with the following function that seems to list all the sensors:

```
def list_sensors(name_pattern=ev3.Sensor.SYSTEM_DEVICE_NAME_CONVENTION, **kwargs):
   classpath = abspath(ev3.Device.DEVICE_ROOT_PATH + '/' + ev3.Sensor.SYSTEM_CLASS_NAME)
   return (ev3.Sensor(name_pattern=name, name_exact=True) 
           for name in ev3.list_device_names(classpath, name_pattern, **kwargs))
```

Is this correct? If so, is it worthwhile adding to the library?

**Comment by dwalton76** [comment]
Assuming you put this in core.py you should replace

- "ev3.Sensor"  with just "Sensor"
- "ev3.Device"  with "Device"
- "ev3.list_device_names" with list_device_names

In general though what you have looks correct and I think it would be worth adding.  Can you submit a pull request with the patch?  Now I am wondering outloud if we have docs on how to do a pull request....if you haven't done this before yell and I will take a first pass at a quick how-to doc.

**Comment by craigsammisutherland** [comment]
Thanks,

I have made the changes and submitted a pull-request. 

There's not a lot of documentation, all I could find was [https://github.com/rhempel/ev3dev-lang-python/blob/develop/CONTRIBUTING.rst](https://github.com/rhempel/ev3dev-lang-python/blob/develop/CONTRIBUTING.rst). So let me know if there is anything else I should do.
