### ISSUE TITLE
Dynamically reloading user code.

### ISSUE THREAD

**Issue by Dave-Baum** [rhempel/ev3dev-lang-python#295]
I've just started playing around with ev3dev and Python, and I noticed that a lot of my edit/debug cycle is eaten up by starting up python and loading the ev3dev modules each time.  I put together a simple module that runs another python script in separate thread, watches for changes to the source file, and then stops the previous invocation and reloads/runs the code again.  This is very convenient when you are making a lot of small tweaks to code.

The rough spot in all of this is stopping the user program's thread(s).  I wanted to avoid forcibly terminating a thread, so instead I'm relying on a cooperative mechanism.  User threads are required to periodically call an idle function in the reloader.  The reloader normally does nothing in this idle function.  However when the reloader wants to stop the program it will raise an exception.  This seems to work well enough except for cases where the waiting is taking place within ev3dev (i.e. wait_while()).

Is there any interest in making this module part of ev3dev?  If so, then the next question is whether we can provide better integration with wait_while() and other such methods.

**Comment by ddemidov** [comment]
Did you consider using [RPyC](http://python-ev3dev.readthedocs.io/en/stable/rpyc.html) paired with an interactive host-side session (like jupyter/ipython) for the interactive editing/debugging?

**Comment by Dave-Baum** [comment]
Thanks for pointing me towards RPyC.  I can see how it would be very handy for interactive sessions.  I'm a little worried about quickly responding to sensors, but maybe the latency is ok.  I'll have to spend some more time using RPyC to see if it is a good alternative to reloading the code from a single process on the ev3 itself.

I still have the problem that something like wait_until() will force me to kill the process and run it again.  It would be nice if this could be aborted.  I'll probably experiment a bit with some custom wait() functions.

**Comment by rhempel** [comment]
Hey @Dave-Baum welcome to ev3dev - glad to see you are back into LEGO robotics!

**Comment by Dave-Baum** [comment]
Hi Ralph - it would be great to catch up, but an Issue Tracker is probably the wrong place :)

I don't think I have a current email address for you.  I'm still at dave at baumfamily dot org.

**Comment by ensonic** [comment]
@Dave-Baum, feel free to look at what I did for open-roberta.org here: https://github.com/OpenRoberta/robertalab-ev3dev
Maybe we can extract some of the code to provide a 'python-runner-service'.

**Comment by Dave-Baum** [comment]
With RPyC I'm seeing an average of about 70 ms for reading a single sensor value, compared to 3.6 ms for code running on the ev3.  Driving around at normal speeds results in stopping 1/4" to 1/2" later, and line following is only reliable at slow speeds.

While this is probably fine for computation-intensive tasks (because you gain the faster host speed over most of the code), it isn't a great fit for the kinds of things I normally write.  Reloading modified .py files into a long-running python session is still a win - at least for my development habits.

**Comment by ddemidov** [comment]
That's a nice piece of information! We should add this to the RPyC page in the documentation.

**Comment by WasabiFan** [comment]
I'm going to close this. We are working on supporting MicroPython as a Python platform, which dramatically speeds up execution time. If someone is looking specifically for an implementation of live reloading, take a look at the OpenRoberta Lab implementation that @ensonic linked to.
