### ISSUE TITLE
Create color constants for the Lego color sensor results

### ISSUE THREAD

**Issue by fisherds** [rhempel/ev3dev-lang-python#296]
- **ev3dev version:**  4.4.24-16-ev3dev-ev3
- **ev3dev-lang-python version:**0.8.0

For the LEDs there are various constants:
ev3.Leds.LEFT
ev3.Leds.RED
ev3.Leds.GREEN
ev3.Leds.BLACK

Same with motors:
ev3.OUTPUT_B
ev3.OUTPUT_C

It'd be nice if there were handy constants for the results of ColorSensor `color` method
http://python-ev3dev.readthedocs.io/en/latest/sensors.html#special-sensor-classes

For example instead of:
```
color_sensor = ev3.ColorSensor()
if color_sensor.color == 2:
    ev3.Sound.speak("Blue").wait()
```

we could allow users to say:
```
if color_sensor.color == ev3.ColorSensor.Blue:
    ev3.Sound.speak("Blue").wait()
```

Obviously we wouldn't do this for every sensor in the world but for the select "Special Sensor Classes" http://python-ev3dev.readthedocs.io/en/latest/sensors.html#special-sensor-classes it seems reasonable.

**Comment by ddemidov** [comment]
This sounds like a nice idea. I think it would even worth to add the the constants to [ev3dev/ev3dev-lang](https://github.com/ev3dev/ev3dev-lang) specification to make those universal across all language bindings. Would you care to create a pull request/issue there?

**Comment by fisherds** [comment]
Happy to let others drive if someone else is willing? :)
