### ISSUE TITLE
Add named getters to check "state" of motor

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#297]
Currently, to my knowledge at least, if you want to check a motor's state you have to do something like this:

```python
if m.STATE_OVERLOADED in m.state:
    print("Overloaded")
```

That's hard to discover if you don't know what you are looking for. I think it would be nice to add a method or property getter to make this easier:

```python
if m.is_overloaded:
    # ...
```

Thoughts? I can open a PR if this makes sense.

**Comment by ddemidov** [comment]
:+1: but may be the PR should be to [spec.json](https://github.com/ev3dev/ev3dev-lang/blob/develop/spec.json#L14) first?

**Comment by ddemidov** [comment]
> but may be the PR should be to spec.json first?

In fact, spec.json [has everything we need](https://github.com/ev3dev/ev3dev-lang/blob/b34680f210de2bb49edf2b5eee93ae5b8c264c8d/spec.json#L318-L347) to implement this.

**Comment by WasabiFan** [comment]
Oh, cool; I didn't recall this already being there. I might find some time today/tomorrow to update templates to use that data.

**Comment by WasabiFan** [comment]
That obviously didn't happen :grin: I guess this is up for grabs if anyone's interested.
