### ISSUE TITLE
Clean up disparate documentation sources

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#298]
Currently, if I do a search online for something Python/ev3dev-related, I get documentation results from three sources:
- <http://ddemidov.github.io/ev3dev-lang-python>
- <http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/>
- <http://ev3dev-lang-python.readthedocs.io/>

It's not clear to me as a new user (or a co-maintainer, for that matter) which one I am supposed to be using. Can we decommission the separate site (or make it extremely obvious that it's old) and remove one of the two other instances?

**Comment by ddemidov** [comment]
- [x] http://ddemidov.github.io/ev3dev-lang-python. I just got rid of this.
- [x] http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/. This is just a link to our primary documentation, which is registered as a subproject of ev3dev-lang on readthedocs.org. We can get rid of that too, if you think we have to.
- [ ] http://ev3dev-lang-python.readthedocs.io/. This is owned by @rhempel, so we need his help to get rid of it (delete the project from readthedocs.org).

**Comment by WasabiFan** [comment]
It looks like there were some unexpected effects here on my end. My hope was to make it so that there was a canonical URL for documentation, but not make either of the latter two dead links -- preferably it would be a redirect. However, it looks like the ev3dev-lang.* one is entirely gone, which broke a couple links that I'm aware of (and likely more). Can we re-open that one?

Sorry for the lack of clarity!

**Comment by ddemidov** [comment]
Restored the second link.

**Comment by WasabiFan** [comment]
I'd say this can be closed; everything that can be done has been done, within reason.
