### ISSUE TITLE
make notes related tables "private" in the Sound class

### ISSUE THREAD

**Issue by ericpascual** [rhempel/ev3dev-lang-python#307]
The names of these attributes make them public from the documentation generation point of view, which adds some "noise" in the result. 

Since they are not supposed to be seen from the class users, it would be better if they were prefixed by an underscore for them not appearing in the generated documentation.

**Comment by ericpascual** [comment]
how can I assign this issue to myself ?

**Comment by ddemidov** [comment]
Only project maintainers can do this I believe.

**Comment by ericpascual** [comment]
@ddemidov I was suspecting this. Thanks.

**Comment by ddemidov** [comment]
Resolved by #308
