### ISSUE TITLE
Color sensor example dies not work

### ISSUE THREAD

**Issue by clplaneguy** [rhempel/ev3dev-lang-python#313]
I have 	(Printed 3/11/2017)

The Hewlett-Packard has 
Windows 7 Home Premium, Service Pack 1
MobaXterm:
	“MobaXterm_Setup_9.4” (from Downloads folder)
"MobaXterm Personal Edition V9.4" (from MobaXterm)
PyCharm:
pycharm-community-2016.3.2 (from Downloads folder)
PyCharm Community Edition 2016.3.2 (from PyCharm Community Edition)
Java 8: 
Java Runtime Environment
"jre1.8.0_121"; "Java 8.01210.13: 8 update 121 (8u121) (64-bit)” (Source Unknown)
Java Development Kit
“jdk-8u121-windows-x64” (from Downloads folder)
"jdk1.8.0_121"	(Source unknown)
"Java 8.01210.13: 8 update 121 (8u121) (64-bit)” (Source Unknown)
"Python 3.6.0 (32 bit)"
"Python 3.5.1 (64 bit)"
Eclipse:
	“eclipse-inst-win32” (from Downloads folder) (Installed)?
	“eclipse-inst-win64” (from Downloads folder) (not Installed)?
"Eclipse IDE for C/C++ Developers"; "Version: Neon.2 Release (4.6.2)"; "Build id: 20161208-0600" (from Eclipse)
 leJOS EV3 Plug-in 		(Source: Marketplace)
	“Eclipse Versions:
		Kelpler (4.3)
		Neon (4.6)
	Date Created: Thu, 2014-03-20 14:43
	Date Updated: Mon, 2016-11-07 14:11”

The Dell has
Windows 10
"MobaXterm Personal Edition V9.4"
PyCharm
Java 8; "jdk1.8.0_121"; "Java 8.01210.13: 8 update 121 (8u121) (64-bit)" jdk or jre?
Java 8; "jre1.8.0_121"; "Java 8.01210.13: 8 update 121 (8u121) (64-bit)" jdk or jre?
"Python 3.6.0 (32 bit)"
"Python 3.5.1 (64 bit)"
"Eclipse IDE for Java Developers"; "Version: Kepler Service Release 1"; "Build id: 0130919-0819" (32 bit)

The EV3 has:
"Lego Mindstorms EV3 Programmable Brick Revision 0006"
"Brickman v0.8.0 2014-2015"

The EV3 16GB SD Card "EV3dev" has: 
Brickman v0.8.0 The ev3dev Brick Manager © 2014-2015 ev3dev.org
ev3dev
ev3dev "Python3.4.2((defalt,oct 8 2014:47:30"
ev3dev-jessie-ev3-generic-2016-12-21
https://github.com/ev3dev/ev3dev/releases/download/ev3dev-jessie-2017-02-11/ev3dev-jessie-ev3-generic-2017-02-11.zip
LEGO MINDSTORMS EV3(211 MiB)
“uname -r” is  “4.4.32-17-ev3dev-ev3”

The EV3 16GB SD Card "leJOS" has:
LeJOS: 
	“leJOS_EV3_0.9.0-beta_win32_setup” (from Downloads folder) (not Installed) 
	“leJOS_EV3_0.9.1-beta_win32_setup” (from Downloads folder) (Installed)
"Mon Nov 16, 2015 5:29 pm   leJOS EV3 0.9.1-beta release is now out - see https://lejosnews.wordpress.com/2015/11"; "leJOS EV3 0.9.1-beta"
"leJOS:0.9.1-beta"	(from the EV3 brick) (Installed)
"Menu:  0.9.1"		(from the EV3 brick) (Installed)
Java 7 (EV3)    
“ejre-7u60-fcs-b19-linux-arm-sflt-headless-07_may_2014.tar” (one of the two) (from Downloads folder)
“ejre-7u75-fcs-b13-linux-arm-sflt-headless-18_dec_2014.tar” (one of the two)   (from Downloads folder)     

           
I have extensive knowledge of FORTRAN, Pascal, Assembler and maybe BASIC. Because I now have a MakeBlock Ultimate 2.0 kit(robot), I now have one month of experience with Scratch and C/C++. Because I now have a Lego MINDSTORMS EV3, I now have two weeks of experience with EV3-G and Putty/MobaXterm/MobaTextEditor/ev3Dev/PyCharm/PyDev/EV3Python. I now have one week of experience with leJOS, two days experience with Java, one day experience with linix and one hour experience with the EV3 API.

I have experience with the book MAXIMUM (2014) by Brian Bagnall and the website leJOS Forums (live). [url][https://sourceforge.net/p/lejos/wiki/Home/[/url] ] by gloomyandy. Information from MAXIMUM and leJOS Forums are sometimes contradictory. If I have explicit instructions from leJOS Forums I will use that. An uncertainty arises when information from MAXIMUM is not explicitly contradicted by leJOS Forums. MAXIMUM states that Java 8 on the PC and Java 7 on the EV3 is fine. Now, with explicit instructions from leJOS Forums to be consistent with the versions, I will use all version 7.

MAXIMUM states that the leJOS EV3 plugin does not run under Eclipse 64bit. That it only runs under Eclipse x32. So, Eclipse x32 must be installed. That is what I have. Please advise.

It seems that the current versions of Eclipse are Neon. The Kepler versions of Eclipse are old and not supported any more.

???It seems that Eclipse does not use Java 1.7 but rather the Java 1.7 mode of Java 1.8() 
 “JavaSE-1.7 (jre8.0_121)”???

I have Java 1.7 installed. Program runs.

Brian’s book sends me in the direction that I want to go.

**Now, everything has changed.  I have an SD card for EV3dev “EV3dev”**
**Now, everything has changed.  I have an SD card for EV3dev “EV3dev”**

The EV3 16GB SD Card "EV3dev" has: 
Brickman v0.8.0 The ev3dev Brick Manager © 2014-2015 ev3dev.org
ev3dev
ev3dev "Python3.4.2((defalt,oct 8 2014:47:30"
ev3dev-jessie-ev3-generic-2016-12-21
https://github.com/ev3dev/ev3dev/releases/download/ev3dev-jessie-2017-02-11/ev3dev-jessie-ev3-generic-2017-02-11.zip
LEGO MINDSTORMS EV3(211 MiB)
“uname -r” is “4.4.32-17-ev3dev-ev3”

But the thing is so small that I cannot find it.  So, I made a new one and am trying to rebuild the SD card/EV3dev/Python/PID6.py But I am getting an error message that I never got before.  Python cannot find the color sensor. I am using the sample program as follows:

```
#!/usr/bin/env python3
from ev3dev.ev3 import *
from time import sleep

# import fcntl
# Connect EV3 color sensor and check connected.

cl = ColorSensor()
assert cl.connected, "Connect a color sensor to any sensor port"

# Put the color sensor into COL-REFLECT mode
# to measure reflected light intensity.
# In this mode the sensor will return a value between 0 and 100
cl.mode = 'COL-REFLECT'

while True:
    print(cl.value())
    sleep(0.5)

# I get max 80 with white paper, 3mm separation
# and 5 with black plastic, same separation
```

I get the eror message as follows:

```
C:\Users\CL_Plane_Guy\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/CL_Plane_Guy/Documents/MobaXterm/slash/RemoteFiles/263120_3_0/Test.py
WARNING: Failed to import fcntl. Button class will be unuseable!
Traceback (most recent call last):
  File "C:/Users/CL_Plane_Guy/Documents/MobaXterm/slash/RemoteFiles/263120_3_0/Test.py", line 8, in <module>
    assert cl.connected, "Connect a color sensor to any sensor port"
AssertionError: Connect a color sensor to any sensor port

Process finished with exit code 1

```

**Comment by ddemidov** [comment]
It looks like you are running the script on your windows PC, instead of launching it on the EV3.

**Comment by WasabiFan** [comment]
I'm going to close this because there's a reasonable resolution and the OP hasn't said that it is still an issue.
