### ISSUE TITLE
Parameter propagation across motor command function calls

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#314]
Currently, due to the fact that we're invoking commands through the file system, calling motor command functions in sequence retains parameters from one call to the next:

```python
m.run_timed(time_sp=3000, speed_sp=500)
m.run_timed(time_sp=3000) # This will run at 500 units/sec

m.run_timed(time_sp=3000, speed_sp=500)
m.run_timed(speed_sp=500) # This will run for 3000 ms
```

In some cases, this is a useful and reasonable behavior: retaining the speed setpoint can make sense. However, there are also cases where this _isn't_ logical functionality: maintaining the time setpoint will rarely be desired.

This effect is largely a result of implementation details without an intentional choice to back it up, so I wanted to bring it up for discussion. If we wanted to counteract this effect, we could enforce values for properties that aren't specified; but this breaks the case of manually setting properties then calling the command method without parameters.

What do others think? Is there value in changing this behavior?

**Comment by ddemidov** [comment]
```python
m.run_timed(time_sp=3000, speed_sp=500)
m.run_timed(time_sp=3000) # This will run at 500 units/sec

m.run_timed(time_sp=3000, speed_sp=500)
m.run_timed(speed_sp=500) # This will run for 3000 ms
```

I think those are really desired behaviours. This way we can save a couple of file accesses (no need to write to `speed_sp` or `time_sp` if they already contain the required values). Also, in the second example, if one does not want to run with `time_sp=3000`, one should really set the needed value explicitly. Otherwise, any value, including a default one, could be a surprise.

Also, this closely mimics the low-level (bash?) interface, and so keeps the functionality similar across language bindings.

**Comment by ddemidov** [comment]
May be something like this would make sense:
```py
with savestate(motor1, motor2):
    # commands involving motor1 and motor2
```

`savestate(device1, device2, ...)` would save state of the listes devices and restore it on exit.

**Comment by WasabiFan** [comment]
I think it's reasonable to stick with the existing propagation functionality; as you said, it's a useful default, and changing the behavior would be difficult.

> with savestate(motor1, motor2):

I like that syntax; it would definitely be an advanced feature, but for those who want to use it, it would clean up some consuming code by a fair bit. This is fairly low-priority, though.

**Comment by dwalton76** [comment]
'Also, this closely mimics the low-level (bash?) interface, and so keeps the functionality similar across language bindings'

+1

**Comment by WasabiFan** [comment]
I'm going to close this. As we implement "friendly" interfaces we'll need to take this behavior into account, but I think this is the confirmed expected behavior for the existing scenario.
