### ISSUE TITLE
Buttons are always pressed

### ISSUE THREAD

**Issue by pipothy** [rhempel/ev3dev-lang-python#321]
I am trying to make a piece of code where I want any button press to interrupt the loop. I am doing so exactly as the examples do, and the documentation suggests:

btn = Button()

while not btn.any():
    [Insert code here]

However, it seems that this doesn't work and the loop never initiates. I checked the buttons_pressed and it shows all buttons pressed, but none of them have been pressed at all. Any idea why, or how I solve this?

Using EV3Dev's latest flash file, Python 3.4.2.

**Comment by ddemidov** [comment]
This might be related to #286, #288. That is, you have ev3dev kernel and the python library out of sync.

**Comment by WasabiFan** [comment]
This is why we ask for specific version numbers :wink: You need to tell us the version number of both ev3dev and python-ev3dev.

**Comment by pipothy** [comment]
Hi all, thanks a lot!

Kernel version is 4.4.32-17-ev3dev-ev3
python-ev3dev is 0.8.1.

I assume I need to do an upgrade...

**Comment by ddemidov** [comment]
Yes, the inverted buttons issue was fixed in [18-ev3dev kernel.](http://www.ev3dev.org/news/2017/01/25/kernel-release-cycle-18/).

**Comment by ensonic** [comment]
Close issue?

**Comment by pipothy** [comment]
This did indeed fix it so yes, this can be closed
