### ISSUE TITLE
Question: BeaconSeeker conflicting with IR remote signals

### ISSUE THREAD

**Issue by Passiday** [rhempel/ev3dev-lang-python#328]
- ev3dev version: 4.4.68-20-ev3dev-ev3
- ev3dev-lang-python version: 0.8.1 (from ev3dev/version.py)

The `core.py` that comes with the `python3-ev3dev` package doesn't seem to have the `BeaconSeeker` class what is already present in the docs. Not sure when it is planned to be included, but nevertheless I have copied the class code out from this repo and experimented with it:
~~~~python
import ev3dev.ev3 as ev3
from BeaconSeeker import BeaconSeeker

ev3.BeaconSeeker = BeaconSeeker

rc = ev3.RemoteControl()
bs = ev3.BeaconSeeker()

cont = True
while(cont):
  print("Heading:", bs.heading, ", distance:" , bs.distance)
  if rc.blue_down:
    cont = False
~~~~
My simple program reports the beacon direction and distance and was supposed to stop only when I press the blue-down on the remote. However, I discovered that the program stops at some specific beacon locations (no blue-down button pressed). Apparently, this behavior is due to the IR sensor mode: when it's in the `IR-SEEK` mode, the property values read from `ev3.RemoteControl()`, like `blue_down`, do not really properly report the button state.

I think am incompetent to suggest how this should be solved, but from what I see in the `BeaconSeeker` class code, it also sets the IR sensor mode only at init, so if some other code changes the mode, also the `BeaconSeeker` will report wrong values. I guess it should check what the mode is (and change the mode) before reporting the property values, and the same should be done for the `RemoteControl` class.

**Comment by ddemidov** [comment]
I don't think its even possible to use RC buttons in beacon mode with the stock software. When you press `beacon` button on the RC, a green LED lights up to indicate its in beacon mode now. As soon as you press any other button, the LED is turned off, and the RC stops transmitting the IR signal.

**Comment by Passiday** [comment]
That's true, but in my particular test code that shouldn't matter, as the program exits when the blue-down is pushed. Does the RC signal protocol contain information about the mode? Or the IR sensor mode at the receiving end just has to be matched with whatever the RC currently is set up to (beacon on/off).

**Comment by Passiday** [comment]
Ok, thanks. This basically closes the issue. Its somewhat sad, though, because it is not possible to make a failsafe program: if the program expects the remote buttons to be pushed but the user turns on the beacon, the program will behave erratically.
