### ISSUE TITLE
NFS : cannot access shared folder 

### ISSUE THREAD

**Issue by calliastrophile** [rhempel/ev3dev-lang-python#332]
I followed the tutorial of setting up NFS file sharing but at the last step after I entered "ls /home/robot/nfs/ev3dev", it said "no such file or directory." The file path that that should be entered was not stated clearly on the tutorial either. What exactly should be the file path to enter in order to see the files in my shared folder? Thanks a lot.

**Comment by WasabiFan** [comment]
You'll get better support at http://github.com/ev3dev/ev3dev/issues. This repo is for the Python language library for ev3dev, but not general usage of the platform.

**Comment by dlech** [comment]
mkdir -p /home/robot/nfs/ev3dev

But, NFS doesn't seem to be working well for other people. https://github.com/ev3dev/ev3dev/issues/905
