### ISSUE TITLE
Is it possible to control the acceleration of the motors?

### ISSUE THREAD

**Issue by Anikaaaa** [rhempel/ev3dev-lang-python#334]
Is it possible to control the acceleration of the motors? So far I only find how to set the speed of the EV3 motors and how to move toward a set point. But I would like to turn the motors with a given acceleration

**Comment by ddemidov** [comment]
There is [`ramp_up_sp`](http://python-ev3dev.readthedocs.io/en/stable/motors.html#ev3dev.core.Motor.ramp_up_sp) and [`ramp_down_sp`](http://python-ev3dev.readthedocs.io/en/stable/motors.html#ev3dev.core.Motor.ramp_down_sp) attributes which I think may help you. Also see tacho-motor documentation [here](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/motors.html#tacho-motor-subsystem).

**Comment by Anikaaaa** [comment]
Thank you for your respond. If I understand it right with  ramp_up_sp and ramp_down_sp a desired speed (speed_sp) should be know. In my case there is no desired speed. I want to turn the motors  with a given desired acceleration. This desired acceleration changes every time step. Is there something like 'acceleration_sp', which makes sure the motor will turn at a given acceleration?

**Comment by ddemidov** [comment]
I don't think that is directly possible. I guess you could use a bit of math and, knowing that 
`a = dv/dt `, or `v(t+dt) = v(t) + a dt`, control the speed (via [`run_direct`](http://python-ev3dev.readthedocs.io/en/stable/motors.html#ev3dev.core.Motor.run_direct)) to get the desired acceleration. I also guess that would be horribly inaccurate. May be @dlech has better ideas?

**Comment by Anikaaaa** [comment]
yes, that is what I'm using right know. But as you say its not accurate enough.

**Comment by dlech** [comment]
Using currently available software, `run_direct` is as good as it gets. Depending on how ambitious you are, you could write your own kernel driver and get slightly better or you could write a PRU firmware and have something like a hard realtime system.

**Comment by dwalton76** [comment]
@Anikaaaa ok to close this one?
