### ISSUE TITLE
What other robots do we need in "demo"?

### ISSUE THREAD

**Issue by dwalton76** [rhempel/ev3dev-lang-python#338]
Do you guys think we could attract more users to ev3dev if it shipped with working code for the base ev3 robot designs? @dlech would you be open to including a `/home/robot/demo/` folder in ev3dev?

Of the 5 [base models](https://www.lego.com/en-us/mindstorms/build-a-robot) we have three of them
- TRACK3R (done)
- SPIK3R
- R3PTAR (done)
- GRIPP3R (tank)
- EV3RSTORM (done)

The 12 fan models are
- BOBB3E (tank)
- BANNER PRINTER
- RAC3 TRUCK (tank)
- DINOR3X
- KRAZ3 (tank)
- EV3D4 (done)
- ELECTRIC GUITAR
- EV3MEG (tank) - looks like a line follower which we do not have a demo of
- EV3 GAME
- MR BEAM
- ROBODOZER (tank)
- WACKEM

For all of the Tank robots the only real thing to program for any of them would be controlling the medium motor and we have examples of this in our TRACKER and EV3D4 demos. So not sure there would be a ton of gain but they also wouldn't be much work (ignoring construction time).  The exception there would be EV3MEG since it looks like a line follower.

I'm not sure how popular all of these others are.  I built SPIK3R once but the controls on it were very clunky.  I also built WACKEM, it was neat just because it was very different.

thoughts?

**Comment by WasabiFan** [comment]
I think @ddemidov has some of this from his original work with ev3dev.

**Comment by ddemidov** [comment]
https://bitbucket.org/d_demidov/ev3-robots/src. But there is not that much code in there; most of these scripts are very simple and don't have any educational value. I think it would be more fun for newcomers to write these from scratch than to copy from somewhere (it would be for me).

**Comment by dlech** [comment]
> @dlech would you be open to including a /home/robot/demo/ folder in ev3dev?

I'm certainly open to it. Some things to think about though:
1. ev3dev-jessie is "done" so I'm not keen on making any significant changes to it.
2. If we add this in ev3dev-stretch, who will be responsible for keeping it up to date if there are breaking changes? (ev3dev-lang-python is already broken in ev3dev-stretch.)
3. Would it better to ship example code via GitHub so that people can actually open the files on a real computer? Example: https://github.com/ev3dev/vscode-hello-python
4. Maybe just include a demo for one robot (e.g. Laurens Valk's EXPLOR3R) in the SD card image so that people can make their robot do *something* before figuring out download programs.

**Comment by WasabiFan** [comment]
> ev3dev-lang-python is already broken in ev3dev-stretch

How so? That seems pretty important. Can you open a new issue for it?

**Comment by dwalton76** [comment]
1. Agreed...stretch would be the place for this

2. I will throw my hat in the ring to help maintain them but would be good if at least one more person signed up. I'm using ev3dev-Lang-Python and haven't hit any issues but I am on dev. What problems have you seen?

3 & 4: We can point them at the demo folder in our repo here. Or we could make our demo folder a sub-repo and just have ev3dev already have it git cloned into '/home/robot/demo/'?

My motivation here...I met the Seshan brothers a few weeks ago and talked to them about ev3dev. They aren't using it much anymore "because it is too difficult for our followers to get it up and running". I think we should make it as easy as possible for users to kick the tires on ev3dev and having working code in the install for some of the more popular robots would have to help.

**Comment by dlech** [comment]
> What problems have you seen?

Someone has to keep up with breaking changes in a timely manner (within 2-4 weeks would be nice)
 
see #339 

> 3 & 4

IMHO, having demo programs in a separate repo would be the easiest way

**Comment by dwalton76** [comment]
within 2-4 weeks should be doable

Once we get 1.0 out and #339 fixed I'll create a repo just for the demos and move them there (assuming no objections).

**Comment by dwalton76** [comment]
![ev3-poll](https://user-images.githubusercontent.com/468309/30041207-3965ff76-91b6-11e7-93dc-e43309ce3302.png)

Results of the poll I posted on the EV3 group on facebook.  I did not know that EVERSTORM was that popular, I imagine being the build on the box is a significant factor.

**Comment by ndward** [comment]
It seems to me that this page is strongly oriented towards models that can be built only with the retail version of the EV3 and that the most important EV3 model of them all, which can be made with both the retail and education versions, has been omitted. I'm referring to the official Lego 'Driving Base' model, also called the 'Robot Educator' model. It's used for all the exercises in the Robot Educator lessons of the education version of the EV3 software and it's also used in many other pedagogical contexts such as the official Lego EV3 Coding Activities downloadable from https://education.lego.com/en-us/downloads/mindstorms-ev3. Very interestingly, Lego provides not only EV3-G solution to those exercises but also RobotC solutions. (I'm working to make a set of EV3dev Python solutions.) Build instructions for making the Driving Base with the education kit can be found at http://robotsquare.com/wp-content/uploads/2013/10/45544_educator.pdf  and instructions on the slight modifications needed to make a very similar model with the retail kit can be found at https://sites.google.com/site/gask3t/lego-ev3/building-plans/educator-vehicle-retail-kit-version . The wheels in the education version are 1.3 times larger in diameter than the wheels in the retail version so some adjustments may also be needed in scripts. The driving base is superior to most models for its versatility – it's very easy to attach multiple sensors. Listen to Lego model designer Lee Magpili explaining why this is his favorite model at https://youtu.be/34zmrFv4k88?t=3m3s. 
Also missing from this discussion are the other 4 standard models that can be built with the education kit: the puppy, the gyroboy, the robot arm and a color sorter.
By the way, does anyone know roughly the ratio of educational kits sold to retail kits sold?

**Comment by dwalton76** [comment]
![survey](https://user-images.githubusercontent.com/468309/30506029-870b6124-9a46-11e7-9a35-81a0c5834f18.png)

Final survey results

**Comment by dwalton76** [comment]
I think doing the "Driving Base" is a good idea. Also based on the survey GRIPP3R would also be good to have.

> Also missing from this discussion are the other 4 standard models that can be built with the education kit: the puppy, the gyroboy, the robot arm and a color sorter.
By the way, does anyone know roughly the ratio of educational kits sold to retail kits sold?

I'm not sure.  I do not own the educational kit but I think at this point own most of the parts it has that the normal kit doesn't have.  I don't know anyone who has the educational kit.

**Comment by dwalton76** [comment]
@dlech can you create an ev3dev-lang-python-demo repo at https://github.com/ev3dev . Once we have that I'll move the demos we have here to there and file issues to add GRIPP3R and the Driving Base.

**Comment by dlech** [comment]
Done. https://github.com/ev3dev/ev3dev-lang-python-demo

**Comment by ddemidov** [comment]
Do we want the demos to be implemented in the current, or in the future 'high level' API?

**Comment by dlech** [comment]
high level :smiley:

**Comment by dwalton76** [comment]
yep since we are doing the EV3-G APIs we should make the demos use them to keep things nice and simple for anyone new to ev3dev python

**Comment by dwalton76** [comment]
demo content has been moved to https://github.com/ev3dev/ev3dev-lang-python-demo
