### ISSUE TITLE
Implement __str__ for motors and sensors

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#341]
When using motors and sensors on the command line, there's some info I'd like to have easy access to; I think it would be reasonable to implement this as the `__str__` method on those objects. I'm specifically interested in:

- Driver
- Port
- Connected?

**Comment by dwalton76** [comment]
We have `__str__` today with the Port info already
https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/core.py#L168-L172

Most programs (all of mine it seems) barf if whatever motor/sensor they are looking for isn't connected.  I suppose someone could have done a try/except around it and at that point the Connected status would be useful but 99% of the time it will just be stating "yes" or "connected".

Driver...unless new drivers are getting loaded mid-program this feels like it would be a bit verbose for `__str__`....`__str__` will be printed a lot in debugs so it is good if it isn't too large.

**Comment by WasabiFan** [comment]
What am I missing?

```
>>> m = ev3.Motor()
>>> m
<ev3dev.core.Motor object at 0xb6caea48>
```

**Comment by dwalton76** [comment]
try `print(m)`

**Comment by WasabiFan** [comment]
Slightly closer...

```
>>> m = ev3.Motor()
>>> print(m)
Motor
```

Modified topic: Implement `__repr__` to print the above information.

**Comment by WasabiFan** [comment]
I'm going to close this as it isn't a significant problem (and, really, has no effect unless you're using the REPL).
