### ISSUE TITLE
Cannot find the version number

### ISSUE THREAD

**Issue by laszewsk** [rhempel/ev3dev-lang-python#55]
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    version=git_version(),
  File "/Users/big/j/ev3dev-lang-python/git_version.py", line 74, in git_version
    raise ValueError("Cannot find the version number!")
ValueError: Cannot find the version number!

**Comment by rhempel** [comment]
I know - working on it.

**Comment by dlech** [comment]
This is because there are no annotated tags. @rhempel, you need to tag releases with `git tag -a`

**Comment by laszewsk** [comment]
I propose to actually use git tags than you get the version number form git tags. Thats what i do in my codes.

https://github.com/cloudmesh/client/blob/master/bin/new_version.sh <https://github.com/cloudmesh/client/blob/master/bin/new_version.sh>

here is what i sometimes do I have that in a Makefile. 
git tag
echo "New Tag?"; read TAG
git tag $TAG
echo $TAG
echo \"$TAG\"" > RELEASE-VERSION
git commit -m "version $TAG" RELEASE-VERSION
python setup.py install
git commit -m $TAG --allow-empty
git push origin --tags
git push

**Comment by rhempel** [comment]
I just pushed an annotated 0.4.2 tag - ReadTheDocs still not building

**Comment by rhempel** [comment]
Yay - ReadTheDocs finally builds correctly - not sure what the issue was but we're all good now.
@laszewsk - if your `python setup.py install` works from the [latest commit][https://github.com/rhempel/ev3dev-lang-python/commit/6132b16a1944eb062048842b513a314244c189d1] please close this issue.

**Comment by laszewsk** [comment]
Works now
