### ISSUE TITLE
easy_install issues: arm-linux-gnueabi-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by laszewsk** [rhempel/ev3dev-lang-python#59]
As I install from source, this is not an issue for me, but others may want to look at this

dpkg-reconfigure tzdata

 apt-get update
 apt-get updateapt-get upgrade
 apt-get upgrade
 apt-get dist-upgrade
 reboot

 apt-get install git
 apt-get install ipython-notebook
 apt-get install libboost-python1.55.0 python-setuptools python-pil
 
easy_install -U python-ev3dev

Searching for python-ev3dev
Reading https://pypi.python.org/simple/python-ev3dev/
Best match: python-ev3dev 0.4.2
Downloading https://pypi.python.org/packages/source/p/python-ev3dev/python-ev3dev-0.4.2.tar.gz#md5=a02c7785adf40b2adbb23775435974de
Processing python-ev3dev-0.4.2.tar.gz
Writing /tmp/easy_install-a7xReP/python-ev3dev-0.4.2/setup.cfg
Running python-ev3dev-0.4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a7xReP/python-ev3dev-0.4.2/egg-dist-tmp-uLkYle
file ev3dev.py (for module ev3dev) not found
file ev3dev.py (for module ev3dev) not found
file ev3dev.py (for module ev3dev) not found
warning: install_lib: 'build/lib.linux-armv5tejl-2.7' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Adding python-ev3dev 0.4.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/python_ev3dev-0.4.2-py2.7.egg
Processing dependencies for python-ev3dev
Searching for pil
Reading https://pypi.python.org/simple/pil/
Reading http://effbot.org/downloads/#Imaging
Reading http://effbot.org/zone/pil-changes-115.htm
Reading http://www.pythonware.com/products/pil
Best match: PIL 1.1.7
Downloading http://effbot.org/media/downloads/PIL-1.1.7.tar.gz
Processing PIL-1.1.7.tar.gz
Writing /tmp/easy_install-5M64tm/PIL-1.1.7/setup.cfg
Running PIL-1.1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5M64tm/PIL-1.1.7/egg-dist-tmp-2y1Ul4
WARNING: '' not a valid package name; please use only.-separated package names in setup.py
unable to execute 'arm-linux-gnueabi-gcc': No such file or directory
error: Setup script exited with error: command 'arm-linux-gnueabi-gcc' failed with exit status 1

**Comment by ddemidov** [comment]
I thi error was fixed in #57 and #56, but that would be available on pypi only when @rhempel tags a new version.

**Comment by ddemidov** [comment]
Also, libboost-python1.55.0 is no longer required as a prerequisite.

**Comment by ddemidov** [comment]
This should be solved with 0.4.3 version.

**Comment by rhempel** [comment]
@laszewsk - please confirm if 0.4.3 addresses your issue - close if yes

**Comment by rhempel** [comment]
I am going to close this issue.
