### ISSUE TITLE
Nice demo files missing

### ISSUE THREAD

**Issue by laszewsk** [rhempel/ev3dev-lang-python#60]
The nice demo files from 

https://github.com/ddemidov/ev3dev-lang-python/tree/master/demo

are missing. I suggest to add them as  it says in the other repo 

"Deprecation warning! This version of python bindings has been deprecated in favor of rhempel/ev3dev-lang-python. This repository is no longer under active developement."

**Comment by ddemidov** [comment]
Duplicate of #47

**Comment by rhempel** [comment]
@laszewsk - if you agree this is a duplicate of #47, please close this one

**Comment by laszewsk** [comment]
duplicate of #47
