### ISSUE TITLE
shoudn't the bindings use their own commands

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#65]
In the code I see a lot of cases like:

```
COMMAND_RUN_FOREVER = 'run-forever'
...
self.command = 'run-forever'
```

Shouldn't the impl use the constants? If okay, I'll send a PR to fix this,

**Comment by ddemidov** [comment]
This does make sense. On the other hand, both `COMMAND_RUN_FOREVER = 'run-forever'` and `self.command = 'run-forever'` are autogenerated from the same `spec.json`, so there is very little chance for these to become de-synchronized.

**Comment by ensonic** [comment]
Thanks for the quick reply, I'll check the autogen facilities and then decide.

**Comment by rhempel** [comment]
Yes, the implementation could use the constants - I think you mean this, right?
```
self.command = COMMAND_RUN_FOREVER
```

**Comment by dwalton76** [comment]
@ensonic did you get a chance to dig into this one?

**Comment by ensonic** [comment]
Nope, was swamped with lots of stuff and now my setup is somewhat outdated ...
