### ISSUE TITLE
file handle cache breaks sensors

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#67]
try this in python (with sensor 0 being the touch sensor):
```
f = open("/sys/class/lego-sensor/sensor0/value0", "r")
print f.readline()
0

f.seek(0)
print f.readline()
0
```

**Comment by ensonic** [comment]
Found a fix. PR is comming in a sec.

**Comment by dlech** [comment]
There is no guarantee that the value returned by the sysfs attribute includes a newline, it is just convention. I think instead of flushing, it might be more efficient to open with no buffering.

    f = open("/sys/class/lego-sensor/sensor0/value0", "r", 0)

These files can't be mmapped (except the `bin_data` attribute).

**Comment by ddemidov** [comment]
I also wonder if replacing `readline` with `read` would also solve this. `readline`-based implementation was only introduced recently.

**Comment by dlech** [comment]
I know from experience that you need to turn off buffering or read() does not work correctly.

**Comment by ddemidov** [comment]
Good to know. I'll do a PR after some testing then.

**Comment by ensonic** [comment]
The flush() is better than nothing, but I can try differently. @ddemidov no need for another PR I can change this one.

**Comment by ddemidov** [comment]
@ensonic, ok, thanks!

**Comment by ensonic** [comment]
PR updated using with with buffering disabled and using read()

**Comment by rhempel** [comment]
Agreed, I merged the PR, if this fixes your issue, please close.
