### ISSUE TITLE
sound.tone is broken

### ISSUE THREAD

**Issue by ensonic** [rhempel/ev3dev-lang-python#82]
```
from ev3dev import ev3 as ev3dev
ev3dev.Sound.tone(100,100).wait()
# or
ev3dev.Sound.tone([(100,100)]).wait()
```
this should only play *one* tone, but plays two instead. The beep command that is generated is '/usr/bin/beep -n -f 100 -l 100' while '/usr/bin/beep -f 100 -l 100' works. The bug is that '-n' should only be used for the *next* tone. PR coming.

**Comment by ddemidov** [comment]
Thanks for confirming this! I thought something was wrong with the sound.
Changing [this line](https://github.com/rhempel/ev3dev-lang-python/pull/80#issuecomment-154718295) to
```py
            return Sound.beep(' -n '.join([beep_args(*t) for t in tone_sequence]))
```
and initializing args in line [2353](https://github.com/rhempel/ev3dev-lang-python/blob/master/ev3dev/core.py#L2353) should do the trick.

**Comment by ddemidov** [comment]
Oops, you did that already.

**Comment by ensonic** [comment]
Jep, just send a PR.
