### ISSUE TITLE
Breaking changes in new kernel

### ISSUE THREAD

**Issue by ddemidov** [rhempel/ev3dev-lang-python#87]
@dlech just [released a new kernel](http://www.ev3dev.org/news/2015/11/09/Kernel-Release-Cycle-8/), which has ev3 leds renamed.

**Comment by ddemidov** [comment]
@ensonic, are you going to switch to the new kernel immediately, or should the fix go after 0.5.0 release?

**Comment by rhempel** [comment]
Please try the ev3dev files in `develop` - they are fully merged with all PRs up to now - I am away from my EV3. If the files are compatible with the new kernel, we can merge into master and tag 0.5.0 
@ddemidov - you have privileges on this repo, so it's OK if you do it.
@ddemidov - can you see the draft (one line so far) release notes for 0.5.0?

**Comment by rhempel** [comment]
Guys, I have fixed my power adapter - no problems getting this merged now.

**Comment by rhempel** [comment]
I'm going to stop working on this tonight  - the LED names still need to be fixed in `spec.json`.

Please check my update to the LED group specs - we cannot have a group name and color name with the same value or the code generator will happily create duplicate class variables.

Setting a color only makes sense for a multicolored LED that is made up of multiple physical LEDS.

**Comment by ddemidov** [comment]
> no problems getting this merged now

This is not a PR (yet). I was just wondering if @ensonic wants this (new led names) to be fixed/introduced now or after 0.5.0.

> @ddemidov - you have privileges on this repo, so it's OK if you do it.
@ddemidov - can you see the draft (one line so far) release notes for 0.5.0?

I don't think I have privileges here, and I also don't see the draft (probably for that same reason). But I guess it does not matter since you got your power adapter fixed :).

**Comment by rhempel** [comment]
@ddemidov - sorry for the botched merge on my end - I think everything is OK.

Now I really will stop before I make things worse, could I ask you (if you have time) to get the latest kernel image and to update the LED names in `spec.json`?

**Comment by ddemidov** [comment]
I'll do this tonight.

**Comment by ddemidov** [comment]
See #88
