### ISSUE TITLE
forgot to annotate the tag for 0.6.0?

### ISSUE THREAD

**Issue by dlech** [rhempel/ev3dev-lang-python#99]
Version 0.6.0 is showing up as 0.5.0post9 [on PyPi](https://pypi.python.org/pypi/python-ev3dev/0.5.0.post9).

**Comment by rhempel** [comment]
Thks David - I'll get it fixed up

**Comment by bittner** [comment]
There is now a [version 0.6.0](https://pypi.python.org/pypi/python-ev3dev) package on PyPi. Unfortunately, the link to the [Package Documentation](http://ddemidov.github.io/ev3dev-lang-python/) there brings you to version `ev3dev 0.2.2.post14`.

**Comment by ddemidov** [comment]
That link was a leftover from the time the package was hosted under my account. I've changed it to point to the new location.

**Comment by rhempel** [comment]
Thks @ddemidov - we'll get things shipshape by the end of the weekend :-)

**Comment by ddemidov** [comment]
My weekend ends 10th of January -- long winter holidays here in Russia :)

**Comment by rhempel** [comment]
Fixed with 212a249951e2674919a3ce87ca57a1aac8745297
